apiVersion: v1
kind: Service
metadata:
  name: orderer4-hktfp
  labels:
    run: orderer4-hktfp
spec:
  type: ClusterIP
  selector:
    name: orderer4
  ports:
    - protocol: TCP
      port: 7450
      name: grpc
