apiVersion: v1
kind: Service
metadata:
  name: peer0-etradeconnect
  labels:
    run: peer0-etradeconnect
spec:
  type: ClusterIP
  selector:
    name: org1peer0
  ports:
    - protocol: TCP
      port: 7051
      name: grpc
    - protocol: TCP
      port: 7053
      name: events
    - protocol: TCP
      port: 7052
      name: chaincode
