apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rca0
  template:
    metadata:
      labels:
        name: rca0
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: rca0
          image: hyperledger/fabric-ca:1.4.7
          command:
            [
              'sh',
              '-c',
              'fabric-ca-server start -d -b rca-org0-admin:rca-org0-adminPW --cfg.identities.allowremove -d --port 6053',
            ]
          env:
            - name: TZ
              value: 'Asia/Hong_Kong'
            - name: FABRIC_CA_SERVER_HOME
              value: /var/artifacts/crypto-config/HktfpMSP/ca/server
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: 'true'
            - name: FABRIC_CA_SERVER_CSR_CN
              value: 'rca-hktfp'
            - name: FABRIC_CA_SERVER_CSR_HOSTS
              value: 0.0.0.0
            - name: FABRIC_CA_SERVER_DEBUG
              value: 'true'
            - name: FABRIC_CA_SERVER_CA_NAME
              value: 'rca-hktfp'
            - name: GODEBUG
              value: 'netdns=go'
          volumeMounts:
            - mountPath: /var/artifacts
              name: fabricfiles
