apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.channel.name }}-config
  namespace: {{ $.Values.metadata.namespace }}
  {{- if $.Values.deployment.annotations }}
    annotations:
{{ toYaml $.Values.deployment.annotations | nindent 8 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ $.Values.channel.name }}-config
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "labels.custom" . | nindent 2 }}
data:
  CHANNEL_NAME: {{ $.Values.channel.name }}
  FABRIC_LOGGING_SPEC: {{ $.Values.peer.loglevel }}
  CORE_PEER_ID: {{ $.Values.peer.name }}.{{ $.Values.metadata.namespace }}
  CORE_PEER_ADDRESS: {{ $.Values.peer.address }}
  CORE_PEER_LOCALMSPID: {{ $.Values.peer.localmspid }}
  CORE_PEER_TLS_ENABLED: "{{ $.Values.peer.tlsstatus }}"
  CORE_PEER_TLS_ROOTCERT_FILE: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/cacerts/ca.crt
  ORDERER_CA: /opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt
  ORDERER_URL: {{ $.Values.orderer.address }}
  CORE_PEER_MSPCONFIGPATH: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: channel-artifacts-{{ $.Values.channel.name }}
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: channel-artifacts-{{ $.Values.channel.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "labels.custom" . | nindent 2 }}
data:
  channel.tx.base64: {{ .Values.channeltx | quote }}
