---
name: openplatform_fabric-Org2MSP
version: 1.0.0

client:
  organization: Org2MSP
  credentialStore:
    path: ./assets/client-certs/hfc-kvs/org2.example.com
    cryptoStore:
      path: ./assets/client-certs/hfc-kvs/org2.example.com
  connection:
    timeout:
      peer:
        endorser: '300'

channels:
  eventstore:
    orderers:
      - orderer1.example.com
    peers:
      peer0.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
      - eventstore:1.0

organizations:
  Org2MSP:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
    certificateAuthorities:
      - rca.org2.example.com
    adminPrivateKey:
      path: ../../deployments/boilerplate/config/../artifacts/Org2MSP/admin/msp/keystore/key.pem
    signedCert:
      path: ../../deployments/boilerplate/config/../artifacts/Org2MSP/admin/msp/signcerts/cert.pem

orderers:
  orderer1.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer1.example.com
    #      grpc-max-send-message-length: 4000
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/OrdererMSP/orderer1.example.com/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem

peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    eventUrl: grpcs://localhost:9053
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/Org2MSP/peer0.org2.example.com/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
  peer1.org2.example.com:
    url: grpcs://localhost:10051
    eventUrl: grpcs://localhost:10053
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/Org2MSP/peer1.org2.example.com/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com

certificateAuthorities:
  rca.org2.example.com:
    url: https://localhost:5055
    caName: rca.org2.example.com
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/Org2MSP/msp/tlscacerts/tls-ca-cert.pem
    registrar:
      - enrollId: rca-org2-admin
        enrollSecret: rca-org2-adminPW
    httpOptions:
      verify: false
