---
name: fdi_openplatform-hsbc
version: 1.0.0

client:
  organization: HsbcMSP
  credentialStore:
    path: ./assets/client-certs/hfc-kvs/hsbc
    cryptoStore:
      path: ./assets/client-certs/hfc-kvs/hsbc
  connection:
    timeout:
      peer:
        endorser: '300'

channels:
  loanapp:
    orderers:
      - orderer0-hktfp
    peers:
      peer0-hsbc:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1-hsbc:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
      - eventstore:1.0

organizations:
  HsbcMSP:
    mspid: HsbcMSP
    peers:
      - peer0-hsbc
      - peer1-hsbc
    certificateAuthorities:
      - rca-hsbc
    adminPrivateKey:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/HsbcMSP/admin/msp/keystore/key.pem
    signedCert:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/HsbcMSP/admin/msp/signcerts/cert.pem

orderers:
  orderer0-hktfp:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer0-hktfp
    #      grpc-max-send-message-length: 4000
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/HktfpMSP/orderer0.hktfp.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem

peers:
  peer0-hsbc:
    url: grpcs://localhost:7451
    eventUrl: grpcs://localhost:7453
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/HsbcMSP/peer0.hsbc.com.hk/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer0-hsbc
  peer1-hsbc:
    url: grpcs://localhost:7551
    eventUrl: grpcs://localhost:7553
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/HsbcMSP/peer1.hsbc.com.hk/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer1-hsbc

certificateAuthorities:
  rca-hsbc:
    url: https://localhost:5054
    caName: rca-hsbc
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/HsbcMSP/peer0.hsbc.com.hk/assets/tls-ca/tls-ca-cert.pem
    registrar:
      - enrollId: rca-hsbc-admin
        enrollSecret: rca-hsbc-adminPW
    httpOptions:
      verify: false
