---
name: fdi_openplatform-pbctfp
version: 1.0.0

client:
  organization: pbctfp
  credentialStore:
    path: ./assets/client-certs/hfc-kvs/pbctfp.net
    cryptoStore:
      path: ./assets/client-certs/hfc-kvs/pbctfp.net
  connection:
    timeout:
      peer:
        endorser: '300'

channels:
  eventstore:
    orderers:
      - orderer0.hktfp.com
    peers:
      peer0.pbctfp.net:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.pbctfp.net:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
      - eventstore:1.0

organizations:
  PbctfpMSP:
    mspid: PbctfpMSP
    peers:
      - peer0.pbctfp.net
      - peer1.pbctfp.net
    certificateAuthorities:
      - rca.pbctfp.net
    adminPrivateKey:
      path: ../../network2/config/../artifacts/crypto-config/PbctfpMSP/admin/msp/keystore/key.pem
    signedCert:
      path: ../../network2/config/../artifacts/crypto-config/PbctfpMSP/admin/msp/signcerts/cert.pem

orderers:
  orderer0.hktfp.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer0.hktfp.com
    #      grpc-max-send-message-length: 4000
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/HktfpMSP/orderer0.hktfp.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem

peers:
  peer0.pbctfp.net:
    url: grpcs://localhost:7251
    eventUrl: grpcs://localhost:7253
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/PbctfpMSP/peer0.pbctfp.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer0.pbctfp.net
  peer1.pbctfp.net:
    url: grpcs://localhost:7351
    eventUrl: grpcs://localhost:7353
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/PbctfpMSP/peer1.pbctfp.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer1.pbctfp.net

certificateAuthorities:
  rca.pbctfp.net:
    url: https://localhost:6055
    caName: rca.pbctfp.net
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/PbctfpMSP/msp/tlscacerts/tls-ca-cert.pem
    registrar:
      - enrollId: rca-pboc-admin
        enrollSecret: rca-pboc-adminPW
    httpOptions:
      verify: false
