apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cli.fullname" . }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "cli.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ template "cli.fullname" . }}
      labels:
    {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc-common
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: cli
          image: "hyperledger/fabric-tools:{{ .Values.image.tag }}"
          command:
            - sh
            - -c
            - "sleep 48h"
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cli.fullname" . }}-config
                  key: TZ
            - name: FABRIC_CFG_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cli.fullname" . }}-config
                  key: FABRIC_CFG_PATH
            - name: GOPATH
              value: /opt/gopath
            - name: FABRIC_LOGGING_SPEC
              value: debug
            - name: CORE_PEER_ID
              value: cli
            - name: CORE_PEER_TLS_ENABLED
              value: 'true'
            - name: CORE_VM_ENDPOINT
              value: 'unix:///host/var/run/docker.sock'
          volumeMounts:
            - mountPath: /var/artifacts
              name: fabricfiles
              subPath: {{ .Values.persistence.subPath }}
            - mountPath: /host/var/run/docker.sock
              name: dockersocket
