apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-org2
  labels:
    app: orgadmin
    release: "admin1"
    namespace: n2
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
