apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gupload2
  labels:
    app: gupload
    release: "g2"
    namespace: n2
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
