apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-p0o2
  labels:
    app: hlf-peer
    release: "p0o1"
    namespace: n1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-p0o2db
  labels:
    app: hlf-couchdb
    release: "p0o2db"
    namespace: n2
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
