apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  selector:
    matchLabels:
      name: fabricfiles
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
