apiVersion: v1
kind: Service
metadata:
  name: orderer1-hktfp
  labels:
    run: orderer1-hktfp
spec:
  type: ClusterIP
  selector:
    name: orderer1
  ports:
    - protocol: TCP
      port: 7150
      name: grpc
