version: "3"

networks:
  relay-net:

services:

  relay-server:
    container_name: relay-server
    image: hktfp5/relay
    restart: unless-stopped
    depends_on:
      - mock-server
      - redis-pubsub
    environment:
      - TARGET_URL=http://mock-server:4001
      - SERVICE_PORT=2500
      - REDIS_HOST=redis-pubsub
      - REDIS_PORT=6379
      - REDIS_TOPIC=request-notify
    volumes:
      - ./relay-logs:/home/app/logs
    ports:
      - 80:2500
    networks:
      - relay-net

  mock-server:
    container_name: mock-server
    image: hktfp5/relay
    restart: unless-stopped
    command: dist/__mocks__/mockEndpoint.js
    networks:
      - relay-net

  redis-pubsub:
    container_name: redis-pubsub
    image: redis
    restart: unless-stopped
    networks:
      - relay-net