apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hlf-peer.fullname" . }}--peer
  labels:
{{ include "labels.standard" . | indent 4 }}
data:
  CORE_PEER_ADDRESSAUTODETECT: "true"
  CORE_PEER_ID: {{ include "hlf-peer.fullname" . }}
  CORE_PEER_NETWORKID: nid1
  # If we have an ingress, we set hostname to it
#  {{- if .Values.ingress.enabled }}
#  CORE_PEER_ADDRESS: {{ index .Values.ingress.hosts 0 }}:7051
#  {{- else }}
#  # Otherwise we use CORE_PEER_ADDRESSAUTODETECT to auto-detect its address
#  {{- end }}
  CORE_PEER_ADDRESS: {{ include "hlf-peer.fullname" . }}:7051
  CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
  CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
  CORE_VM_DOCKER_ATTACHOUT: "true"
  CORE_PEER_EVENTS_ADDRESS: 0.0.0.0:7053
  CORE_PEER_COMMITTER_ENABLED: "true"
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_PEER_DISCOVERY_PERIOD: 60s
  CORE_PEER_DISCOVERY_TOUCHPERIOD: 60s
  CORE_PEER_LOCALMSPID: {{ .Values.global.mspId | quote }}
  CORE_PEER_MSPCONFIGPATH: "{{ include "hlf-peer.home" . }}/msp"
  ###########
  # Logging #
  ###########
  FABRIC_LOGGING_SPEC: {{ .Values.logging.level }}
  CORE_LOGGING_PEER: {{ .Values.logging.peer | quote }}
  CORE_LOGGING_CAUTHDSL: {{ .Values.logging.cauthdsl | quote }}
  CORE_LOGGING_GOSSIP: {{ .Values.logging.gossip | quote }}
  CORE_LOGGING_LEDGER: {{ .Values.logging.ledger | quote }}
  CORE_LOGGING_MSP: {{ .Values.logging.msp | quote }}
  CORE_LOGGING_POLICIES: {{ .Values.logging.policies | quote }}
  CORE_LOGGING_GRPC: {{ .Values.logging.grpc | quote }}
  ##########
  # Gossip #
  ##########
  CORE_PEER_GOSSIP_BOOTSTRAP: {{ .Values.peer.gossip.bootstrap | quote }}
  CORE_PEER_GOSSIP_ENDPOINT: {{ .Values.peer.gossip.endpoint | quote }}
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: {{ .Values.peer.gossip.externalEndpoint | quote }}
  CORE_PEER_GOSSIP_ORGLEADER: {{ .Values.peer.gossip.orgLeader | quote }}
  CORE_PEER_GOSSIP_USELEADERELECTION: {{ .Values.peer.gossip.useLeaderElection | quote }}
  #############
  # CHAINCODE #
  #############
  {{- if .Values.peer.chaincode.builder }}
  CORE_CHAINCODE_BUILDER: {{ .Values.peer.chaincode.builder | quote }}
  {{- end}}
  {{- if .Values.peer.chaincode.runtime.golang }}
  CORE_CHAINCODE_GOLANG_RUNTIME: {{ .Values.peer.chaincode.runtime.golang | quote }}
  {{- end}}
  {{- if .Values.peer.chaincode.runtime.java }}
  CORE_CHAINCODE_JAVA_RUNTIME: {{ .Values.peer.chaincode.runtime.java | quote }}
  {{- end}}
  {{- if .Values.peer.chaincode.runtime.node }}
  CORE_CHAINCODE_NODE_RUNTIME: {{ .Values.peer.chaincode.runtime.node | quote }}
  {{- end}}
  ##########
  # TLS    #
  ##########
  CORE_PEER_TLS_ENABLED: {{ .Values.peer.tls.server.enabled | quote }}
  CORE_PEER_TLS_CERT_FILE: "{{ include "hlf-peer.home" . }}/tls-msp/tls/tls.crt"
  CORE_PEER_TLS_KEY_FILE: "{{ include "hlf-peer.home" . }}/tls-msp/tls/tls.key"
  CORE_PEER_TLS_ROOTCERT_FILE: "{{ include "hlf-peer.home" . }}/tls-msp/tlscacerts/tlscacert.pem"
  CORE_PEER_TLS_CLIENTROOTCAS_FILES: "[{{ include "hlf-peer.home" . }}/tls-msp/tlscacerts/tlscacert.pem]"
  CORE_PEER_TLS_CLIENTCERT_FILE: "{{ include "hlf-peer.home" . }}/tls-msp/tls/tls.crt"
  CORE_PEER_TLS_CLIENTKEY_FILE: "{{ include "hlf-peer.home" . }}/tls-msp/tls/tls.key"
  CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
  CORE_LEDGER_STATE_STATEDATABASE: {{ .Values.peer.databaseType | quote }}
  # Containers in the same pod share the host
  {{- if eq .Values.peer.databaseType "CouchDB" }}
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: "{{ .Values.peer.couchdbInstance }}-hlf-couchdb:5984"
  CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: {{ .Values.peer.couchdbUsername | quote }}
  CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: {{ .Values.peer.couchdbPassword | quote }}
  {{- end }}
  PEER_CFG_PATH: "{{ include "hlf-peer.home" . }}/config"
  FABRIC_CFG_PATH: "{{ include "hlf-peer.home" . }}/fabric_cfg"
  # https://golang.org/pkg/net/#:~:text=A%20numeric%20netdns%20setting%2C%20as,%3Dnetdns%3Dgo%2B1.
  # https://medium.com/@Alibaba_Cloud/hyperledger-fabric-deployment-on-alibaba-cloud-environment-sigsegv-problem-analysis-and-solutions-9a708313f1a4
  GODEBUG: "netdns=go"
  ADMIN_MSP_PATH: "{{ include "hlf-peer.home" . }}/admin/msp"
  ORD_TLS_PATH: "{{ include "hlf-peer.home" . }}/ord/org0/tlscacerts"
  CORE_METRICS_PROVIDER: prometheus
  CORE_OPERATIONS_LISTENADDRESS: ":9443"
