{{- range .Values.externalService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
{{ include "labels.standard" $ | indent 4 }}
spec:
  type: ExternalName
  externalName: {{ .externalName }}
---
{{- end }}
