apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-ord.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ord-port
      protocol: TCP
      name: grpc
    {{- if .Values.sidecar.isalive.enabled }}
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: isalive
    {{- end }}
  selector:
    app: {{ include "hlf-ord.name" . }}
    release: {{ .Release.Name }}
