export const UNAUTHORIZED_ACCESS = 'unauthorized access';
export const MISSING_VARIABLE = 'Cannot convert undefined or null to object';
export const USER_NOT_FOUND = 'could not find user';
export const PEER_INFO_ERROR = 'unknown peer info error';
export const IDENTITY_ALREADY_EXIST = 'Identity already exists in the wallet';
export const MISSING_CONNECTION_PROFILE = 'missing path to connection profile';
export const MISSING_FABRIC_NETWORK = 'missing path to fabric network';
export const MISSING_CHANNELNAME = 'missing channelName';
export const MISSING_WALLET = 'missing wallet';
