apiVersion: v1
kind: Service
metadata:
  name: {{ include "gupload.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.ingress.type }}
  ports:
    - port: 1313
      targetPort: 1313
      protocol: TCP
      name: request
  selector:
    app: {{ include "gupload.name" . }}
    release: {{ .Release.Name }}
