kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ord0
  labels:
    app: hlf-ord
    release: "o0"
    namespace: n0
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ord1
  labels:
    app: hlf-ord
    release: "o1"
    namespace: n0
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ord2
  labels:
    app: hlf-ord
    release: "o2"
    namespace: n0
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ord3
  labels:
    app: hlf-ord
    release: "o3"
    namespace: n0
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ord4
  labels:
    app: hlf-ord
    release: "o4"
    namespace: n0
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
