global:
  logging: info
  workingDir: /var/hyperledger
  mspId: Org2MSP
  config:
    setupsh: admin2-orgadmin--setupsh
    coreyaml: admin2-orgadmin--core

job:
  bootstrap: false
  addorg: true


persistence:
  pvcName: pvc-org2
