persistence:
  enabled: true
  pvcName: pvc-p0o2db

##################################
## Further configuration options #
##################################
## Database username
couchdbUsername: "couchdb"
## Database password (default: random 24 character string)
couchdbPassword: "password"
