global:
  ### Default
  # TZ: Asia/Hong_Kong
  ### Default
  # workingDir: /var/hyperledger/crypto-config
  ### Default
  # logging: info
  mspId: Org2MSP
  caName: tlsca2

caAdmin: tlsca2-admin
caAdminPW: tlsca2-adminPW

### Default
#image:
#  repository: hyperledger/fabric-ca
#  tag: 1.4.7
#  pullPolicy: IfNotPresent

### Default
service:
  type: NodePort
  port: 7054

config:
  type: tls
  ### Default
  # debug: false
  csr:
    names:
      c: US
      st: "North Carolina"
      o: Hyperledger
      ou: Fabric
  affiliations: {}
  ## "intermediate" is only specified for Intermediate CA's
  # intermediate:
  #   parent:
  #     chart: parent-ca
  #     url: parent-ca.example.com
  #     port: 7054
  ## Affiliations used in ca Server configuration file

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - tlsca2
  tls: []

persistence:
  ### Default
  # enabled: true
  existingClaim: pvc-org2

externalDatabase:
  type: postgres
  host: admin2-postgresql-0
  port: 5432
  database: tls_ca_db
  username: postgres
  password: password

### Default
#db:
#  ssl: disable
