apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gupload1
  labels:
    app: gupload
    release: "g1"
    namespace: n1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
