global:
  logging: info
  workingDir: /var/hyperledger
  mspId: Org1MSP
  config:
    setupsh: admin1-orgadmin--setupsh
    coreyaml: admin1-orgadmin--core

job:
  singletask: true
    fetchChannelConfig: true
  bootstrap: false
  addorg: false

persistence:
  pvcName: pvc-org1
