global:
  mspId: Org1MSP
  caName: rca1
  caServerHome: /var/hyperledger/crypto-config/Org1MSP/ca/server
  caClientHome: /var/hyperledger/crypto-config/Org1MSP/ca/admin
  domain: org1.net

caAdmin: rca1-admin
caAdminPW: rca1-adminPW
endpoint: rca1-hlf-ca.n1.svc.cluster.local:7054

#fabricCaClientTlsCertfiles: /var/hyperledger/crypto-config/Org0MSP/ca/server/ca-cert.pem
orgCaCert: /var/hyperledger/crypto-config/Org1MSP/ca/admin/msp/cacerts/rca1-hlf-ca-n1-svc-cluster-local-7054.pem
adminCert: /var/hyperledger/crypto-config/Org1MSP/admin/msp/signcerts/cert.pem

orgAdmin:
  enabled: true
  id: admin-peer0.org1.net
  secret: admin-peer0.org1.netPW
  type: admin
  attrs: "hf.Registrar.Attributes=*,hf.Revoker=true,hf.GenCRL=true,admin=true:ecert"

items:
  - type: type
    id: peer0.org1.net
    secret: peer0.org1.netPW
    caClientMspDir: msp
    csrHosts: "p0o1-hlf-peer,peer0.org1.net,127.0.0.1"

persistence:
  pvcName: pvc-org1
