apiVersion: v2
name: cli
description: Helm chart for Fabric cli
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: common
    version: 0.3.1
    repository: https://charts.bitnami.com/bitnami
