version: '2'

networks:
  openplatform:

services:
# ORG3
  gw-org3:
    image: fabric-es/gw-org3:1.0
    container_name: gw-org3
    environment:
      - AUTHORIZATION_SERVER_URI=http://auth-server3:8080/oauth/authenticate
      - CA_ENROLLMENT_ID_ADMIN=rca-org3-admin
      - CA_ENROLLMENT_SECRET_ADMIN=rca-org3-adminPW
      - CONNECTION_PROFILE=/home/app/packages/gw-org3/connection/connection-org3.docker.yaml
      - ORG_ADMIN_ID=admin-org3.net
      - ORG_ADMIN_SECRET=admin-org3.netPW
      - ORG_CA_URL=https://rca-org3:5056
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=4001
      - TEMP_REMOTE_URI=http://gw-org1:4001/graphql\ http://gw-org2:4001/graphql
    working_dir: /home/app/packages/gw-org3
    ports:
      - 4003:4001
    networks:
      - openplatform
    depends_on:
      - auth-server3
      - orderer0-org0
      - peer0-org3
    volumes:
      - $VOLUME/gw-org3/assets/:/home/app/packages/gw-org3/assets/
      - $VOLUME/gw-org3/logs/:/home/app/packages/gw-org3/logs/
      - $ARTIFACTS/crypto-config/:/var/artifacts/crypto-config/
