version: '2'

networks:
  openplatform:

services:
  tester:
    environment:
      - TEST_TARGETS=gw-org1 4001 gw-org2 4001
    image: $TEST_IMAGE
    container_name: tester
    working_dir: /home/app/packages/tester
    networks:
      - openplatform
  # command: ["jest", "integration.test"]
