version: '2'

networks:
  openplatform:

services:
  eventstore-cc1:
    image: "${CC_IMAGE}"
    container_name: eventstore-cc1
    environment:
      - CHAINCODE_ADDRESS="0.0.0.0:7052"
      - CHAINCODE_CCID
    ports:
      - 7052:7052
    networks:
      - openplatform
