version: '2'

networks:
  openplatform:

services:
  rl-org2:
    image: fabric-es/rl-org2:$RELEASE
    container_name: rl-org2
    environment:
      - CONNECTION_PROFILE=/home/app/packages/rl-org2/connection/connection-org2.docker.yaml
      - AUTHORIZATION_SERVER_URI=http://auth-server2:8080/oauth/authenticate
      - CA_ENROLLMENT_ID_ADMIN=rca-org2-admin
      - CA_ENROLLMENT_SECRET_ADMIN=rca-org2-adminPW
      - ORG_CA_URL=https://rca-org2:5054
      - ORG_ADMIN_ID=admin-org2.net
      - ORG_ADMIN_SECRET=admin-org2.netPW
      - REDIS_HOST=redis02
      - RELAY_HOST=rl-org2
      - TARGET_URL=https://192.168.0.188:4322
      - SERVER_KEY=/var/keys/wildcard_etradeconnect.key
      - SERVER_CERT=/var/keys/star_etradeconnect_net.cer
      - LOG_LEVEL=$LOG_LEVEL
      - LOG_TARGET=$LOG_TARGET
    working_dir: /home/app/packages/rl-org2
    ports:
      - 2502:2502
      - 2503:2503
    networks:
      - openplatform
    depends_on:
      - auth-server2
      - orderer0-org0
      - peer0-org2
    volumes:
      - $VOLUME/rl-org2/assets/:/home/app/packages/rl-org2/assets/
      - $VOLUME/rl-org2/logs/:/home/app/packages/rl-org2/logs/
      - $ARTIFACTS/crypto-config/:/var/artifacts/crypto-config/
      - /Users/paul/cert/OV/:/var/keys/
