version: '2'

networks:
  openplatform:

services:
  postgres02:
    container_name: postgres02
    image: postgres:9.6.17-alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    # - POSTGRES_INITDB_ARGS=--max_files_per_process=200
    volumes:
      - $ARTIFACTS/postgres02:/var/lib/postgresql/data
      - $SCRIPTS/createdb.sql:/docker-entrypoint-initdb.d/1-createdb.sql
      - $SCRIPTS/init-auth-db.sh:/docker-entrypoint-initdb.d/2-init-auth-db.sh
    command: postgres
    ports:
      - 5432
    networks:
      - openplatform

  redis02:
    container_name: redis02
    image: $REDISEARCH_IMAGE
    volumes:
      - $VOLUME/redis-data02:/data
    # custom configuration. will require if AUTH is set
    # - $VOLUME/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379
    networks:
      - openplatform
