version: '2'

networks:
  openplatform:

services:
# ORG1
  postgres01:
    container_name: postgres01
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - $ARTIFACTS/postgres01:/var/lib/postgresql/data
      - $SCRIPTS/createdb.sql:/docker-entrypoint-initdb.d/1-createdb.sql
    command: postgres
    networks:
      - openplatform

# ORG2
  postgres02:
    container_name: postgres02
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - $ARTIFACTS/postgres02:/var/lib/postgresql/data
      - $SCRIPTS/createdb.sql:/docker-entrypoint-initdb.d/1-createdb.sql
    command: postgres
    networks:
      - openplatform
