version: '2'

networks:
  openplatform:

services:
  postgres01:
    container_name: postgres01
    image: postgres:9.6.17-alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - $ARTIFACTS/postgres01:/var/lib/postgresql/data
      - $SCRIPTS/createdb.sql:/docker-entrypoint-initdb.d/1-createdb.sql
    command: postgres
    ports:
      - 5432:5432
    networks:
      - openplatform

  redis01:
    container_name: redis01
    image: redis:6.0.3-alpine
    volumes:
      - $VOLUME/redis-data01:/data
    # custom configuration. will require if AUTH is set
    # - $VOLUME/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - openplatform

  proxy01:
    image: $PROXY_IMAGE
    container_name: proxy01
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - AUTH_HOST=http://auth-server1:8080
      - APP_HOST=http://ui-account1:3000
      - GW_ORG_HOST=http://gw-org1:4001
    ports:
      - 3001:8080
    networks:
      - openplatform
