version: '2'

networks:
  openplatform:

services:
  auth-server1:
    image: $AUTH_IMAGE
    container_name: auth-server1
    environment:
      - PORT=8080
      - TYPEORM_HOST=postgres01
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
      - TYPEORM_PORT=5432
      - REDIS_HOST=redis01
      - REDIS_PORT=6379
      - JWT_SECRET=secret
      - JWT_EXP_IN_SECOND=900
      - REFRESH_TOKEN_EXP_IN_SEC=86400
      - ORG_ADMIN_ID=admin-org1.net
      - ORG_ADMIN_SECRET=admin-org1.netPW
      - ORG_ADMIN_EMAIL=admin@org1.net
      - CLIENT_APPLICATION_NAME=root_client
      - CLIENT_SECRET=password
      - LOG_LEVEL=$LOG_LEVEL
      - LOG_TARGET=$LOG_TARGET
    # this open port for development of ui, should be removed for production
    ports:
      - 8080:8080
    networks:
      - openplatform
    depends_on:
      - redis01
      - postgres01
