version: "2"

networks:
  openplatform:

services:
  gw-org3:
    image: fabric-es/gw-org3:$RELEASE
    container_name: gw-org3
    environment:
      - CONNECTION_PROFILE=/home/app/packages/gw-org3/connection/connection.gw-org3.docker.yaml
      - AUTHORIZATION_SERVER_URI=http://auth-server3:8080/oauth/authenticate
      - CA_ENROLLMENT_ID_ADMIN=rca-org3-admin
      - CA_ENROLLMENT_SECRET_ADMIN=rca-org3-adminPW
      - CA_NAME=rca-org3
      # - ORG_CA_URL=https://rca-org3:5353
      - ORG_ADMIN_ID=admin-org3.net
      - ORG_ADMIN_SECRET=admin-org3.netPW
      - GATEWAY_HOST=gw-org3
      - REDIS_HOST=redis3
      - QUERY_PORT=5003
      - ORGURL=http://gw-org3:4001/graphql
      # - CERT_PATH_CERT=/cert/org3.crt
      # - CERT_PATH_KEY=/cert/org3.key
      # - NODE_EXTRA_CA_CERTS=/cert/ca.crt
    working_dir: /home/app/packages/gw-org3
    ports:
      - 4003:4001
      - 5003:5003
    networks:
      - openplatform
    depends_on:
      - auth-server3
      - redis3
      - orderer0-org0
      - peer0-org3
    volumes:
      # - $VOLUME/gw-org3/assets/:/home/app/packages/gw-org3/assets/
      # - $VOLUME/gw-org3/logs/:/home/app/packages/gw-org3/logs/
      - $ARTIFACTS/crypto-config/:/var/artifacts/crypto-config/
      - $CERTS:/cert
