version: '2'

networks:
  openplatform:

services:
  postgres01:
    container_name: postgres01
    image: postgres:9.6.20
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - $ARTIFACTS/postgres01:/var/lib/postgresql/data
      - $SCRIPTS/createdb.sql:/docker-entrypoint-initdb.d/1-createdb.sql
    command: postgres
    # this open port for development, should be removed for production
    ports:
      - 5432:5432
    networks:
      - openplatform

  redis01:
    container_name: redis01
    image: redislabs/redisearch:1.8.3
    volumes:
      - $VOLUME/redis-data01:/data
    # custom configuration. will require if AUTH is set
    # - $VOLUME/redis.conf:/usr/local/etc/redis/redis.conf
    # this open port for development, should be removed for production
    ports:
      - 6379:6379
    networks:
      - openplatform
