version: '2'

networks:
  openplatform:

services:
  tls-ca-hktfp:
    extends:
      file: compose.1.2org.yaml
      service: tls-ca-hktfp
  rca-hktfp:
    extends:
      file: compose.1.2org.yaml
      service: rca-hktfp
  rca-etradeconnect:
    extends:
      file: compose.1.2org.yaml
      service: rca-etradeconnect
  rca-pbctfp:
    extends:
      file: compose.1.2org.yaml
      service: rca-pbctfp
  peer0-etradeconnect:
    extends:
      file: compose.1.2org.yaml
      service: peer0-etradeconnect
  peer0-pbctfp:
    extends:
      file: compose.1.2org.yaml
      service: peer0-pbctfp
  orderer0-hktfp:
    extends:
      file: compose.1.2org.yaml
      service: orderer0-hktfp
  cli:
    extends:
      file: compose.1.2org.yaml
      service: cli
  postgres01:
    extends:
      file: compose.1.2org.yaml
      service: postgres01
  postgres02:
    extends:
      file: compose.1.2org.yaml
      service: postgres02

  auth-server1:
    image: espresso/auth-server:1.0
    container_name: auth-server1
    environment:
      - TYPEORM_HOST=postgres01
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
    ports:
      - 3901:8080
    depends_on:
      - postgres01
    volumes:
      - $VOLUME/auth-server1/logs/:/home/app/packages/authentication/logs/
    networks:
      - openplatform

  auth-server2:
    image: espresso/auth-server:1.0
    container_name: auth-server2
    environment:
      - TYPEORM_HOST=postgres02
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
    ports:
      - 3902:8080
    depends_on:
      - postgres02
    volumes:
      - $VOLUME/auth-server2/logs/:/home/app/packages/authentication/logs/
    networks:
      - openplatform

  gw-org1:
    image: espresso/gw-org1:1.0
    container_name: gw-org1
    environment:
      - AUTHORIZATION_SERVER_URI=http://auth-server1/oauth/authenticate
      - CA_ENROLLMENT_ID_ADMIN=rca-etradeconnect-admin
      - CA_ENROLLMENT_SECRET_ADMIN=rca-etradeconnect-adminPW
      - CHANNEL_HUB=peer0-etradeconnect
      - CONNECTION_PROFILE=/home/app/packages/gw-org1/connection/connection-org1.docker.yaml
      - COLLECTION=etcPrivateDetails
      - ORG_ADMIN_ID=admin-etradeconnect.net
      - ORG_ADMIN_SECRET=Heym2rQK
      - ORG_CA_URL=https://rca-etradeconnect:6054
      - PEER_NAME=peer0-etradeconnect
      - GATEWAY_HOST=0.0.0.0
    working_dir: /home/app/packages/gw-org1
    ports:
      - 4011:4001
    networks:
      - openplatform
    depends_on:
      - auth-server1
      - orderer0-hktfp
      - peer0-etradeconnect
    volumes:
      - $VOLUME/gw-org1/assets/:/home/app/packages/gw-org1/assets/
      - $VOLUME/gw-org1/logs/:/home/app/packages/gw-org1/logs/
      - $ARTIFACTS/crypto-config/:/var/artifacts/crypto-config/

  gw-org2:
    image: espresso/gw-org2:1.0
    container_name: gw-org2
    environment:
      - AUTHORIZATION_SERVER_URI=http://auth-server2/oauth/authenticate
      - CA_ENROLLMENT_ID_ADMIN=rca-pboc-admin
      - CA_ENROLLMENT_SECRET_ADMIN=rca-pboc-adminPW
      - CHANNEL_HUB=peer0-pbctfp
      - CONNECTION_PROFILE=/home/app/packages/gw-org2/connection/connection-org2.docker.yaml
      - COLLECTION=pbctfpPrivateDetails
      - ORG_ADMIN_ID=admin-pbctfp.net
      - ORG_ADMIN_SECRET=mEN6bpQW
      - ORG_CA_URL=https://rca-pbctfp:6055
      - PEER_NAME=peer0-pbctfp
      - GATEWAY_HOST=0.0.0.0
    working_dir: /home/app/packages/gw-org2
    ports:
      - 4012:4002
    networks:
      - openplatform
    depends_on:
      - auth-server2
      - orderer0-hktfp
      - peer0-pbctfp
    volumes:
      - $VOLUME/gw-org2/assets/:/home/app/packages/gw-org2/assets/
      - $VOLUME/gw-org2/logs/:/home/app/packages/gw-org2/logs/
      - $ARTIFACTS/crypto-config/:/var/artifacts/crypto-config/

  tester:
    image: espresso/tester:1.0
    container_name: tester
    working_dir: /home/app/packages/tester
    networks:
      - openplatform
    command: ["yarn", "test"]
