version: '2'

networks:
  openplatform:

services:
  tester:
    environment:
      - TEST_TARGETS=relay-pboc
      - TEST_OPTIONS=https://tester:4321
      - SERVER_KEY=/var/keys/wildcard_etradeconnect.key
      - SERVER_CERT=/var/keys/star_etradeconnect_net.cer
      - LOG_LEVEL=$LOG_LEVEL
      - LOG_TARGET=$LOG_TARGET
      - BATCH_NUM=10
      - RUNS_NUM=1000
      - RUNS_WAIT=60000
      - READ_RETRY=30
      - READ_WAIT=3500
    image: $TEST_IMAGE
    container_name: tester
    working_dir: /home/app
    networks:
      - openplatform
    volumes:
      - /Users/paul/cert/OV/:/var/keys/