version: '2'

networks:
  openplatform:

services:
  auth-server2:
    image: $AUTH_IMAGE
    container_name: auth-server2
    environment:
      - PORT=8080
      - TYPEORM_HOST=postgres02
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
      - TYPEORM_PORT=5432
      - REDIS_HOST=redis02
      - REDIS_PORT=6379
      - JWT_SECRET=secret
      - JWT_EXP_IN_SECOND=900
      - REFRESH_TOKEN_EXP_IN_SEC=86400
      - ORG_ADMIN_ID=admin-org2.net
      - ORG_ADMIN_SECRET=admin-org2.netPW
      - ORG_ADMIN_EMAIL=admin@org2.net
      - CLIENT_APPLICATION_NAME=root_client
      - CLIENT_SECRET=password
      - LOG_LEVEL=$LOG_LEVEL
      - LOG_TARGET=$LOG_TARGET
    ports:
      - 8081:8080
    networks:
      - openplatform
    depends_on:
      - redis02
      - postgres02
  # volumes:
  #   - $VOLUME/auth-server2/logs/:/home/app/packages/authentication/logs/
