version: '2'

networks:
  openplatform:

services:
# ORG3
  rca-org3:
    extends:
      file: nodebase.yaml
      service: ca
    container_name: rca-org3
    restart: always
    environment:
      - HYPERLEDGER_VOL=/var/artifacts
      - FABRIC_CA_SERVER_HOME=/var/artifacts/crypto-config/Org3MSP/ca/server
      - FABRIC_CA_SERVER_CSR_CN=rca-org3
      - FABRIC_CA_SERVER_CA_NAME=rca-org3
    ports:
      - 5056:5056
    command: sh -c 'fabric-ca-server start -d -b rca-org3-admin:rca-org3-adminPW --cfg.affiliations.allowremove  --cfg.identities.allowremove --port 5056'
    volumes:
      - $SCRIPTS:/setup
      - $ARTIFACTS:/var/artifacts

  peer0-org3:
    extends:
      file: nodebase.yaml
      service: peer
    container_name: peer0-org3
    environment:
      - CORE_PEER_ID=peer0-org3
      - CORE_PEER_ADDRESS=peer0-org3:7451
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7451
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/Org3MSP/peer0.org3.net/msp
      - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/Org3MSP/peer0.org3.net/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/Org3MSP/peer0.org3.net/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/Org3MSP/peer0.org3.net/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
#     - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org3:7551
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0-org3:7451
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0-org3:7451
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7452
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/Org3MSP/peer0.org3.net
    volumes:
      - /var/run:/host/var/run
      - $ARTIFACTS:/var/artifacts
    ports:
      - 7451:7451
      - 7453:7453
