version: '2'

networks:
  openplatform:

services:
# ORG2
  rca-org2:
    extends:
      file: nodebase.yaml
      service: ca
    container_name: rca-org2
    restart: always
    environment:
      - HYPERLEDGER_VOL=/var/artifacts
      - FABRIC_CA_SERVER_HOME=/var/artifacts/crypto-config/Org2MSP/ca/server
      - FABRIC_CA_SERVER_CSR_CN=rca-org2
      - FABRIC_CA_SERVER_CA_NAME=rca-org2
    ports:
      - 5055:5055
    command: sh -c 'fabric-ca-server start -d -b rca-org2-admin:rca-org2-adminPW --cfg.affiliations.allowremove  --cfg.identities.allowremove --port 5055'
    volumes:
      - $SCRIPTS:/setup
      - $ARTIFACTS:/var/artifacts

  peer0-org2:
    extends:
      file: nodebase.yaml
      service: peer
    container_name: peer0-org2
    environment:
      - CORE_PEER_ID=peer0-org2
      - CORE_PEER_ADDRESS=peer0-org2:7251
      - CORE_PEER_LISTENADDRESS=peer0-org2:7251
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/Org2MSP/peer0.org2.net/msp
      - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/Org2MSP/peer0.org2.net/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/Org2MSP/peer0.org2.net/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/Org2MSP/peer0.org2.net/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
#     - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org2:7351
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0-org2:7251
      - CORE_PEER_GOSSIP_ENDPOINT=peer0-org2:7251
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0-org2:7251
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7252
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/Org2MSP/peer0.org2.net
    volumes:
      - /var/run:/host/var/run
      - $ARTIFACTS:/var/artifacts
      - $CONFIG/bin:/builders/external/bin
      - ./core.yaml:/etc/hyperledger/fabric/core.yaml
    ports:
      - 7251:7251
      - 7253:7253
