version: '2'

networks:
  openplatform:

# Jest
#services:
# tester:
#   environment:
#     - TEST_OPTIONS=jest
#     - TEST_TARGETS=gw-org1 4001 gw-org2 4001
#     - LOG_LEVEL=$LOG_LEVEL
#     - LOG_TARGET=$LOG_TARGET
#   image: $TEST_IMAGE
#   container_name: tester
#   working_dir: /home/app
#   networks:
#     - openplatform

# Ref Impl
services:
  tester:
    environment:
      - TEST_OPTIONS=ref-impl
      - TEST_TARGETS=gw-org1 4001 gw-org2 4001
      - LOG_LEVEL=$LOG_LEVEL
      - LOG_TARGET=$LOG_TARGET
      - RUNS_NUM=10
      - BATCH_NUM=10
      - RUNS_WAIT=60
      - READ_RETRY=10
      - READ_WAIT=3000
    image: $TEST_IMAGE
    container_name: tester
    working_dir: /home/app
    networks:
      - openplatform
