version: '2'

networks:
  openplatform:

services:
  tester:
    environment:
      - TEST_OPTIONS=fab
      - TEST_TARGETS=$TARGET_URL
      - SERVER_KEY=/var/keys/wildcard_etradeconnect.key
      - SERVER_CERT=/var/keys/star_etradeconnect_net.cer
      - AUTH_ON=less
      - LOG_LEVEL=$LOG_LEVEL
      - LOG_TARGET=$LOG_TARGET
      - BATCH_NUM=10
      - RUNS_NUM=5000
      - RUNS_WAIT=65
      - READ_RETRY=100
      - READ_WAIT=3000
      - STATS_DATA=/var/stats/data.json
      - FAB_TEST_RULE=createInvoice
      - RL_ORG1_LOG_PATH=/var/container_share/rl-org1/logs/all.log
      - RL_ORG2_LOG_PATH=/var/container_share/rl-org2/logs/all.log
    image: $TEST_IMAGE
    container_name: tester
    working_dir: /home/app
    networks:
      - openplatform
    volumes:
      - $VOLUME/testers/stats/:/var/stats/
      - /home/hjkicl/cert/:/var/keys/
      - $VOLUME:/var/container_share/
