version: '2'

networks:
    apps_1:

services:

    postgres-1:
        container_name: postgres-1
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
        volumes:
            - /home/web/postgresql/data:/var/lib/postgresql/data
        networks:
            - apps_1

    auth-server-1:
        container_name: auth-server-1
        image: build:5000/auth-server
        restart: always
        depends_on:
            - postgres-1
        environment:
            - TYPEORM_HOST=postgres-1
            - TYPEORM_PORT=5432
            - TYPEORM_USERNAME=postgres
            - TYPEORM_PASSWORD=docker
            - TYPEORM_LOGGING=true
            - TYPEORM_DATABASE=auth_db
        ports:
            - 4100:8080
        networks:
            - apps_1

    gw-org1:
        container_name: gw-org1
        image: build:5000/gw-org1
        restart: always
        depends_on:
            - auth-server-gw-org1
        environment:
            - TYPEORM_HOST=postgres-1
            - TYPEORM_PORT=5432
            - TYPEORM_USERNAME=postgres
            - TYPEORM_PASSWORD=docker
            - TYPEORM_LOGGING=true
            - TYPEORM_DATABASE=auth_db
        working_dir: /home/app/packages/gw-org1
        ports:
            - 4000:4001
        volumes:
            - /home/web/postgresql/data:/var/lib/postgresql/data
        networks:
            - apps_gw-org1
