pipeline {

    agent none

    stages {
        stage('Deploy Apps') {
            parallel {
                stage('Web 1') {
                    agent { label 'web1' }
                    steps {
                        sh "docker-compose -f ./deployments/app-net/cloud/db_org1.yaml up -d"
                        sh "sleep 20"
                        sh "docker-compose -f ./deployments/app-net/cloud/auth_org1.yaml down"
                        sh "docker rmi -f build:5000/auth-server"
                        sh "docker-compose -f ./deployments/app-net/cloud/auth_org1.yaml up -d"
                    }
                }
                stage('Web 2') {
                    agent { label 'web2' }
                    steps {
                        sh "docker-compose -f ./deployments/app-net/cloud/db_org2.yaml up -d"
                        sh "sleep 20"
                        sh "docker-compose -f ./deployments/app-net/cloud/auth_org2.yaml down"
                        sh "docker rmi -f build:5000/auth-server"
                        sh "docker-compose -f ./deployments/app-net/cloud/auth_org2.yaml up -d"
                    }
                }
                stage('Web 3') {
                    agent { label 'web3' }
                    steps {
                        sh "docker-compose -f ./deployments/app-net/cloud/db_org3.yaml up -d"
                        sh "sleep 20"
                        sh "docker-compose -f ./deployments/app-net/cloud/auth_org3.yaml down"
                        sh "docker rmi -f build:5000/auth-server"
                        sh "docker-compose -f ./deployments/app-net/cloud/auth_org3.yaml up -d"
                    }
                }
            }
        }
    }
}