apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-hktfp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db0
  template:
    metadata:
      labels:
        name: db0
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: postgres
          image: postgres:12-alpine
          env:
            - name: TZ
              value: "Asia/Hong_Kong"
            - name: DATABASE_DATABASE
              value: fabricexplorer
            - name: DATABASE_USERNAME
              value: hppoc
            - name: DATABASE_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: fabricfiles
              subPath: db0
            - mountPath: /var/artifacts
              name: fabricfiles
