apiVersion: v1
kind: Service
metadata:
  name: fabric-tools
  labels:
    run: fabric-tools
spec:
  type: ClusterIP
  selector:
    name: fabric-tools
  ports:
    - protocol: TCP
      port: 7050
      name: grpc
