apiVersion: v1
kind: Service
metadata:
  name: orderer3-hktfp
  labels:
    run: orderer3-hktfp
spec:
  type: ClusterIP
  selector:
    name: orderer3
  ports:
    - protocol: TCP
      port: 7350
      name: grpc
