apiVersion: v1
kind: Service
metadata:
  name: orderer0-hktfp
  labels:
    run: orderer0-hktfp
spec:
  type: ClusterIP
  selector:
    name: orderer0
  ports:
    - protocol: TCP
      port: 7050
      name: grpc
