apiVersion: v1
kind: Service
metadata:
  name: peer1-etradeconnect
  labels:
    run: peer1-etradeconnect
spec:
  type: ClusterIP
  selector:
    name: org1peer1
  ports:
    - protocol: TCP
      port: 7151
      name: grpc
    - protocol: TCP
      port: 7153
      name: events
    - protocol: TCP
      port: 7152
      name: chaincode
