apiVersion: v1
kind: PersistentVolume
metadata:
  name: org1peer1-pv
  labels:
    type: local
    name: org1peer1_production
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data_org1peer1
