apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: org2peer0-pv-claim
spec:
  storageClassName: manual
  selector:
    matchLabels:
      name: org2peer0_production
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
