---
name: fdi_openplatform-etc
version: 1.0.0

client:
  organization: etc
  credentialStore:
    path: ./assets/client-certs/hfc-kvs/etradeconnect
    cryptoStore:
      path: ./assets/client-certs/hfc-kvs/etradeconnect
  connection:
    timeout:
      peer:
        endorser: '300'

channels:
  eventstore:
    orderers:
      - orderer0-hktfp
    peers:
      peer0-etradeconnect:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1-etradeconnect:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
      - eventstore:1.0

organizations:
  EtcMSP:
    mspid: EtcMSP
    peers:
      - peer0-etradeconnect
      - peer1-etradeconnect
    certificateAuthorities:
      - rca-etradeconnect
    adminPrivateKey:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/EtcMSP/admin/msp/keystore/key.pem
    signedCert:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/EtcMSP/admin/msp/signcerts/cert.pem

orderers:
  orderer0-hktfp:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer0-hktfp
    #      grpc-max-send-message-length: 4000
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/HktfpMSP/orderer0.hktfp.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem

peers:
  peer0-etradeconnect:
    url: grpcs://localhost:7051
    eventUrl: grpcs://localhost:7053
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/EtcMSP/peer0.etradeconnect.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer0-etradeconnect
  peer1-etradeconnect:
    url: grpcs://localhost:7151
    eventUrl: grpcs://localhost:7153
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/EtcMSP/peer1.etradeconnect.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer1-etradeconnect

certificateAuthorities:
  rca-etradeconnect:
    url: https://localhost:6054
    caName: rca-etradeconnect
    tlsCACerts:
      path: ../../deployments/boilerplate/config/../artifacts/crypto-config/EtcMSP/msp/tlscacerts/tls-ca-cert.pem
    registrar:
      - enrollId: rca-etradeconnect-admin
        enrollSecret: rca-etradeconnect-adminPW
    httpOptions:
      verify: false
