mspId: "Org0MSP"
caAdmin: tlsca0-admin
caAdminPW: tlsca0-adminPW
caName: tlsca0

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
  path: /
  hosts:
    - tlsca0
  tls: []

persistence:
  enabled: true
  annotations: {}
  existingClaim: "pvc-org0"

externalDatabase:
  type: postgres
  host: admin0-postgresql-0
  port: 5432
  database: tls_ca_db
  username: postgres
  password: password

config:
  hlfToolsVersion: 1.4.7
  fabricCaHome: /var/hyperledger/crypto-config/Org0MSP/tls/server
  fabricCaClientHome: /var/hyperledger/crypto-config/Org0MSP/tls/admin
  fabricCaClientTlsCertfiles: /var/hyperledger/crypto-config/Org0MSP/tls/server/ca-cert.pem
  ## Enable debug logging in ca Server configuration file
  debug: false
  csr:
    names:
      c: US
      st: "North Carolina"
      o: Hyperledger
      ou: Fabric
  affiliations: {}
  ## "intermediate" is only specified for Intermediate CA's
  # intermediate:
  #   parent:
  #     chart: parent-ca
  #     url: parent-ca.example.com
  #     port: 7054
  ## Affiliations used in ca Server configuration file
