mspId: Org0MSP
caAdmin: admin
caAdminPW: adminPW
## Name of CA, stored in FABRIC_CA_SERVER_CA_NAME (and the configMap "--config", if deploying a Root CA)
caName: org1-ca

image:
  repository: hyperledger/fabric-ca
  tag: 1.4.7
  pullPolicy: IfNotPresent
