mspId: Org0MSP
caAdmin: rca0-admin
caAdminPW: rca0-adminPW
# Don't change caName for org0
caName: rca0

image:
  repository: hyperledger/fabric-ca
  tag: 1.4.7
  pullPolicy: IfNotPresent

service:
  ## Cluster IP or LoadBalancer
  type: ClusterIP
  port: 7054

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
  path: /
  hosts:
    - rca0
  tls: []
  # secretName is {{ Release.Name }}-tls. For org0, it must be tlsca0-tls
#    - secretName: "tlsca0-tls"
#      hosts:
#        - tlsca0

persistence:
  enabled: true
  storageClass: manual
  accessMode: ReadWriteOnce
  existingClaim: pvc-org0
  # size: 10Mi

externalDatabase:
  type: postgres
  host: admin0-postgresql-0
  port: 5432
  database: rca_db
  username: postgres
  password: password

config:
  hlfToolsVersion: 1.4.7
  fabricCaHome: /var/hyperledger/crypto-config/Org0MSP/ca/server
  fabricCaClientHome: /var/hyperledger/crypto-config/Org0MSP/ca/admin
  fabricCaClientTlsCertfiles: /var/hyperledger/crypto-config/Org0MSP/ca/server/ca-cert.pem
  ## Enable debug logging in ca Server configuration file
  debug: false
  csr:
    names:
      c: US
      st: "North Carolina"
      o: Hyperledger
      ou: Fabric
  affiliations: {}
  ## "intermediate" is only specified for Intermediate CA's
  # intermediate:
  #   parent:
  #     chart: parent-ca
  #     url: parent-ca.example.com
  #     port: 7054
  ## Affiliations used in ca Server configuration file
