mspId: Org0MSP

## rca-org0 properties
caAdmin: rca0-admin
caAdminPW: rca0-adminPW
# Don't change caName for org0
caName: rca0

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
  path: /
  hosts:
    - rca0
  tls: []
    # secretName is {{ Release.Name }}-tls. For org0, it must be rca0-tls
#    - secretName: rca0-tls
#      hosts:
#        - rca0

# connect db by admin0
# host name: {{ Release.Name }}-postgresql-o
# if release of "orgadmin" is changed, the host name is required to change it
externalDatabase:
  type: postgres
  host: admin0-postgresql-0
  port: 5432
  database: rca_db
  username: postgres
  password: password

persistence:
  enabled: true
  annotations: {}
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: ""
  # accessMode: ReadWriteOnce
  # size: 1Gi
  existingClaim: "pvc-org0"

config:
  hlfToolsVersion: 1.4.7
  fabricCaHome: /var/hyperledger/crypto-config/Org0MSP/ca/server
  fabricCaClientHome: /var/hyperledger/crypto-config/Org0MSP/ca/admin
  fabricCaClientTlsCertfiles: /var/hyperledger/crypto-config/Org0MSP/ca/server/ca-cert.pem
  ## Enable debug logging in ca Server configuration file
  debug: false
  csr:
    names:
      c: US
      st: "North Carolina"
      o: Hyperledger
      ou: Fabric
  affiliations: {}
  ## "intermediate" is only specified for Intermediate CA's
  # intermediate:
  #   parent:
  #     chart: parent-ca
  #     url: parent-ca.example.com
  #     port: 7054
  ## Affiliations used in ca Server configuration file
