version: '2'

networks:
    apps_1:

services:

    postgres-1:
        container_name: postgres-1
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
        volumes:
            - /home/web/postgresql/data:/var/lib/postgresql/data
        networks:
            - apps_1
        logging:
            driver: gcplogs

    auth-server-1:
        container_name: auth-server-1
        image: build:5000/auth-server
        restart: always
        depends_on:
            - postgres-1
        environment:
            - TYPEORM_HOST=postgres-1
            - TYPEORM_PORT=5432
            - TYPEORM_USERNAME=postgres
            - TYPEORM_PASSWORD=docker
            - TYPEORM_LOGGING=true
            - TYPEORM_DATABASE=auth_db
        ports:
            - 4100:8080
        networks:
            - apps_1
        logging:
            driver: gcplogs

    gw-org1:
        container_name: gw-org1
        image: build:5000/gw-org1
        restart: "no"
        depends_on:
            - auth-server-1
        environment:
            # Network
            - NODE1=35.213.127.193
            - NODE2=35.213.45.247
            - NODE3=34.84.24.163
            - NODE4=34.84.173.113
            - NODE5=34.85.7.30
            - NODE6=34.84.208.188
            - NODE7=34.84.62.135
            # GW-ORG1
            - ADMINISTRATOR_PORT=15001
            - AUTHORIZATION_SERVER_URI=auth-server-1/oauth/authenticate
            - CA_ENROLLMENT_ID_ADMIN=rca-etradeconnect-admin
            - CA_ENROLLMENT_SECRET_ADMIN=rcMyG7C9U
            - CHAINCODE_ID=eventstore
            - CHANNEL_NAME=loanapp
            - CHANNEL_HUB=peer0.etradeconnect.net
            - COLLECTION=etcPrivateDetails
            - CONNECTION_PROFILE=/home/app/packages/gw-org1/assets/connection.yaml
            - GATEWAY_HOST=localhost
            - GATEWAY_PORT=4001
            - MSPID=EtcMSP
            - NETWORK_LOCATION=/var/artifacts/crypto-config
            - ORG_ADMIN_ID=admin-etradeconnect.net
            - ORG_ADMIN_SECRET=Heym2rQK
            - ORG_CA_URL=https://peer0.etradeconnect.net:6054
            - ORGNAME=etradeconnect.net
            - ORDERER_NAME=orderer0.hktfp.com
            - ORDERER_TLSCA_CERT=/var/artifacts/crypto-config/HktfpMSP/orderer0.hktfp.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - PEER_NAME=peer0.etradeconnect.net
            - SERVICE_DOCUMENT_PORT=14013
            - SERVICE_LOAN_PORT=14012
            - SERVICE_PRIVATE_PORT=14014
            - SERVICE_USER_PORT=14011
            - WALLET=assets/wallet
        working_dir: /home/app/packages/gw-org1
        volumes:
            - /home/web/artifacts/crypto-config:/var/artifacts/crypto-config
            - /home/web/artifacts/gw-org1/assets:/home/app/packages/gw-org1/assets
            - /home/web/artifacts/gw-org1/logs:/home/app/packages/gw-org1/logs
        extra_hosts:
            - "orderer0.hktfp.com:${NODE1}"
            - "orderer1.hktfp.com:${NODE2}"
            - "orderer2.hktfp.com:${NODE3}"
            - "orderer3.hktfp.com:${NODE4}"
            - "orderer4.hktfp.com:${NODE5}"
            - "rca.etradeconnect.net:${NODE2}"
            - "peer0.etradeconnect.net:${NODE2}"
            - "peer1.etradeconnect.net:${NODE3}"
            - "rca.pbctfp.net:${NODE4}"
            - "peer0.pbctfp.net:${NODE4}"
            - "peer1.pbctfp.net:${NODE5}"
            - "rca.credrate.com.hk:${NODE6}"
            - "peer0.credrate.com.hk:${NODE6}"
            - "peer1.credrate.com.hk:${NODE7}"
        ports:
            - 4000:4001
        networks:
            - apps_1

