pipeline {

    agent none

    stages {
        stage('Deploy Apps') {
            parallel {
                stage('Web 1') {
                    agent { label 'web1' }
                    steps {
                        sh "echo \$SHELL"
                        sh "docker-compose -f ./deployments/app-net/cd/gcp1/docker-compose-org1.yaml down"
                        sh "docker rmi -f build:5000/auth-server"
                        sh "docker rmi -f build:5000/gw-org1"
                        sh "docker-compose -f ./deployments/app-net/cd/gcp1/docker-compose-org1.yaml up -d"
                    }
                }
                stage('Web 2') {
                    agent { label 'web2' }
                    steps {
                        sh "docker-compose -f ./deployments/app-net/cd/gcp1/docker-compose-org2.yaml down"
                        sh "docker rmi -f build:5000/auth-server"
                        sh "docker rmi -f build:5000/gw-org2"
                        sh "mkdir -p /home/web/artifacts/gw-org2/assets"
                        sh "cp ./deployments/app-net/cd/gcp1/connection-all.yaml /home/web/artifacts/gw-org2/assets"
                        sh "cp ./deployments/app-net/cd/gcp1/connection-org2.yaml /home/web/artifacts/gw-org2/assets/connection.yaml"
                        sh "docker-compose -f ./deployments/app-net/cd/gcp1/docker-compose-org2.yaml up -d"
                    }
                }
                stage('Web 3') {
                    agent { label 'web3' }
                    steps {
                        sh "docker-compose -f ./deployments/app-net/cd/gcp1/docker-compose-org3.yaml down"
                        sh "docker rmi -f build:5000/auth-server"
                        sh "docker rmi -f build:5000/gw-org3"
                        sh "mkdir -p /home/web/artifacts/gw-org3/assets"
                        sh "cp ./deployments/app-net/cd/gcp1/connection-all.yaml /home/web/artifacts/gw-org3/assets"
                        sh "cp ./deployments/app-net/cd/gcp1/connection-org3.yaml /home/web/artifacts/gw-org3/assets/connection.yaml"
                        sh "docker-compose -f ./deployments/app-net/cd/gcp1/docker-compose-org3.yaml up -d"
                    }
                }
            }
        }
    }
}