apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
spec:
#  hostAliases:
#    - ip: '127.0.0.1'
#      hostnames:
#        - 'fabric-tools'
#    - ip: '10.104.54.113'
#      hostnames:
#        - 'rca.hktfp.com'
#    - ip: '10.109.90.181'
#      hostnames:
#        - 'rca.etradeconnect.net'
#    - ip: '10.108.87.210'
#      hostnames:
#        - 'rca.pbctfp.net'
#    - ip: '10.110.10.122'
#      hostnames:
#        - 'orderer0.hktfp.com'
#    - ip: '10.101.107.162'
#      hostnames:
#        - 'orderer1.hktfp.com'
#    - ip: '10.105.80.240'
#      hostnames:
#        - 'orderer2.hktfp.com'
#    - ip: '10.101.85.41'
#      hostnames:
#        - 'orderer3.hktfp.com'
#    - ip: '10.101.105.49'
#      hostnames:
#        - 'orderer4.hktfp.com'
#    - ip: '10.111.189.116'
#      hostnames:
#        - 'peer0.etradeconnect.net'
#    - ip: '10.99.157.159'
#      hostnames:
#        - 'peer1.etradeconnect.net'
#    - ip: '10.111.251.178'
#      hostnames:
#        - 'peer0.pbctfp.net'
#    - ip: '10.97.226.93'
#      hostnames:
#        - 'peer1.pbctfp.net'
  volumes:
    - name: fabricfiles
      persistentVolumeClaim:
        claimName: task-pv-claim
    - name: dockersocket
      hostPath:
        path: /var/run/docker.sock
  containers:
    - name: fabrictools
      image: hyperledger/fabric-tools:1.4.3
      command: ['sh', '-c', 'sleep 48h']
      env:
        - name: TZ
          value: 'Asia/Hong_Kong'
        - name: FABRIC_CFG_PATH
          value: '/etc/hyperledger/fabric/'
        - name: GOPATH
          value: /opt/gopath
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_TLS_ENABLED
          value: 'true'
        - name: CORE_VM_ENDPOINT
          value: 'unix:///host/var/run/docker.sock'
      volumeMounts:
        - mountPath: /var/artifacts
          name: fabricfiles
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
