apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-pv
  labels:
    type: local
    name: fabricfiles
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data
