apiVersion: v1
kind: Service
metadata:
  name: rca-etradeconnect
  labels:
    run: rca-etradeconnect
spec:
  type: ClusterIP
  selector:
    name: rca1
  ports:
    - protocol: TCP
      port: 6054
      name: grpc
