apiVersion: v1
kind: Service
metadata:
  name: rca-pbctfp
  labels:
    run: rca-pbctfp
spec:
  type: ClusterIP
  selector:
    name: rca2
  ports:
    - protocol: TCP
      port: 6055
      name: grpc
