---
name: openplatform_fabric-Org1MSP
version: 1.0.0

client:
  organization: Org1MSP
  credentialStore:
    path: ./assets/client-certs/hfc-kvs/org1.example.com
    cryptoStore:
      path: ./assets/client-certs/hfc-kvs/org1.example.com
  connection:
    timeout:
      peer:
        endorser: '300'

channels:
  loanapp:
    orderers:
      - orderer0.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
      - eventstore:1.0

organizations:
  Org1MSP:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - rca.org1.example.com
    adminPrivateKey:
      path: ../../deployments/loan-dev-net/config/../artifacts/crypto-config/Org1MSP/admin/msp/keystore/key.pem
    signedCert:
      path: ../../deployments/loan-dev-net/config/../artifacts/crypto-config/Org1MSP/admin/msp/signcerts/cert.pem

orderers:
  orderer0.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer0.example.com
    #      grpc-max-send-message-length: 4000
    tlsCACerts:
      path: ../../deployments/loan-dev-net/config/../artifacts/crypto-config/OrdererMSP/orderer0.example.com/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    eventUrl: grpcs://localhost:7053
    tlsCACerts:
      path: ../../deployments/loan-dev-net/config/../artifacts/crypto-config/Org1MSP/peer0.org1.example.com/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com

certificateAuthorities:
  rca.org1.example.com:
    url: https://localhost:5054
    caName: rca.org1.example.com
    tlsCACerts:
      path: ../../deployments/loan-dev-net/config/../artifacts/crypto-config/Org1MSP/peer0.org1.example.com/assets/tls-ca/tls-ca-cert.pem
    registrar:
      - enrollId: rca-org1-admin
        enrollSecret: rca-org1-adminPW
    httpOptions:
      verify: false
