apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orgadmin.fullname" . }}-cli
  labels:
{{- include "labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "orgadmin.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "labels.standard" . | indent 8 }}
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.pvcName }}
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
        {{- if .Values.ordererConfiguration.enabled }}
        - name: configtx
          configMap:
            name: {{ include "orgadmin.fullname" . }}--configtx
        - name: org1mspcacerts
          secret:
            optional: true
            secretName: {{ .Values.ordererConfiguration.org1cacert }}
        - name: org1mspadmincerts
          secret:
            optional: true
            secretName: {{ .Values.ordererConfiguration.org1admincerts }}
        - name: org1msptlscacerts
          secret:
            optional: true
            secretName: {{ .Values.ordererConfiguration.org1tlscacerts }}
        {{- end }}
      containers:
        - name: cli
          image: "hyperledger/fabric-tools:{{ .Values.cli.image.tag }}"
          workingDir: "/var/hyperledger/cli"
          command:
            - sh
            - -c
            - "sleep 48h"
          envFrom:
            - configMapRef:
                name: {{ include "orgadmin.fullname" . }}--cli
          volumeMounts:
            - mountPath: /var/hyperledger
              name: fabricfiles
            - mountPath: /host/var/run/docker.sock
              name: dockersocket
            {{- if .Values.ordererConfiguration.enabled }}
            - mountPath: /var/hyperledger/cli
              name: configtx
            - mountPath: /var/hyperledger/crypto-config/Org1MSP/msp/cacerts
              readOnly: true
              name: org1mspcacerts
            - mountPath: /var/hyperledger/crypto-config/Org1MSP/msp/admincerts
              readOnly: true
              name: org1mspadmincerts
            - mountPath: /var/hyperledger/crypto-config/Org1MSP/msp/tlscacerts
              readOnly: true
              name: org1msptlscacerts
            {{- end }}
