apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orgadmin.fullname" . }}-cli
  labels:
{{- include "labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "orgadmin.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "labels.standard" . | indent 8 }}
    spec:
      hostAliases:
      {{- range .Values.orderers }}
      - ip: {{ .hostAlias }}
        hostnames:
          - {{ .name }}
      {{- end }}
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.pvcName }}
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
        {{- if .Values.ordererConfiguration.enabled }}
        - name: configtx
          configMap:
            name: {{ include "orgadmin.fullname" . }}--configtx
        - name: org1mspcacerts
          secret:
            optional: true
            secretName: {{ .Values.ordererConfiguration.org1cacert }}
        - name: org1mspadmincerts
          secret:
            optional: true
            secretName: {{ .Values.ordererConfiguration.org1admincerts }}
        - name: org1msptlscacerts
          secret:
            optional: true
            secretName: {{ .Values.ordererConfiguration.org1tlscacerts }}
        {{- end }}
        - name: peerconfig
          configMap:
            name: {{ include "orgadmin.fullname" . }}--peerconfig
        - name: core
          configMap:
            name: {{ include "orgadmin.fullname" . }}--core
        {{- if .Values.cli.channels }}
        {{- range .Values.cli.channels }}
        - name: {{ . }}
          secret:
            optional: true
            secretName: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.cli.ordTlsSignCert }}
        - name: ord-tlssigncert
          secret:
            optional: true
            secretName: {{ .Values.cli.ordTlsSignCert }}
        {{- end }}
        {{- if .Values.cli.anchortx }}
        - name: anchor-tx
          secret:
            optional: true
            secretName: {{ .Values.cli.anchortx }}
        {{- end }}
      containers:
        - name: cli
          image: "hyperledger/fabric-tools:{{ .Values.cli.image.tag }}"
          workingDir: {{ .Values.cli.workingDir | quote }}
          command:
            - sh
            - -c
            - "sleep 48h"
          envFrom:
            - configMapRef:
                name: {{ include "orgadmin.fullname" . }}--cli
          volumeMounts:
            - mountPath: /var/hyperledger
              name: fabricfiles
            - mountPath: /host/var/run/docker.sock
              name: dockersocket
            {{- if .Values.ordererConfiguration.enabled }}
            - mountPath: /var/hyperledger/cli/configtx
              name: configtx
            - mountPath: /var/hyperledger/crypto-config/Org1MSP/msp/cacerts
              readOnly: true
              name: org1mspcacerts
            - mountPath: /var/hyperledger/crypto-config/Org1MSP/msp/admincerts
              readOnly: true
              name: org1mspadmincerts
            - mountPath: /var/hyperledger/crypto-config/Org1MSP/msp/tlscacerts
              readOnly: true
              name: org1msptlscacerts
            {{- end }}
            - mountPath: /var/hyperledger/cli
              name: core
            {{- if .Values.cli.channels }}
            {{- range .Values.cli.channels }}
            - mountPath: "{{ $.Values.cli.channeltxDir }}/{{ . }}"
              name: {{ . }}
            {{- end }}
            {{- end }}
            {{- if .Values.cli.ordTlsSignCert }}
            - mountPath: /var/hyperledger/crypto-config/Org1MSP/peer0.org1.net/ord/tls-msp/signcerts
              name: ord-tlssigncert
            {{- end }}
            {{- if .Values.cli.anchortx }}
            - mountPath: {{ .Values.cli.anchortxDir }}
              name: anchor-tx
            {{- end }}
