{{- if .Values.orderer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: p0o1-hlf-peer
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: ExternalName
  externalName: p0o1-hlf-peer.n1.svc.cluster.local
{{- end }}
