apiVersion: v1
kind: Service
metadata:
  name: explorer-hktfp
  labels:
    run: explorer-hktfp
spec:
  type: ClusterIP
  selector:
    name: explorer-app
  ports:
    - protocol: TCP
      port: 8080
      name: http
