apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: explorer
  template:
    metadata:
      labels:
        name: explorer
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: explorer
          image: hyperledger/explorer:latest
          command: ["sh" , "-c" , "/var/artifacts/explorer/app/run.sh"]
          env:
            - name: TZ
              value: "Asia/Hong_Kong"
            - name: DATABASE_HOST
              value: db-hktfp
            - name: DATABASE_USERNAME
              value: hppoc
            - name: DATABASE_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/artifacts
              name: fabricfiles
