global:
  TZ: Asia/Hong_Kong
  mspId: Org0MSP
  workingDir: /var/hyperledger/crypto-config
  logging: info

cli:
  fabricBinary: "2.2.0"
  fabricCABinary: "1.4.7"
  # It provides org0 with org1's certs, for creation of genesis.block
  firstOrgDir: /var/hyperledger/crypto-config/Org1MSP

orderer:
  enabled: false
  ### certs provided by org1, to org0
#  secret:
#    org1cacert: org1-cacerts
#    org1admincerts: org1-admincerts
#    org1tlscacerts: org1-tlscacerts
#  channels:
#    - "channeltx"

hostAlias:
  enabled: false
  hostnames:
    - hostname: peer0.org1.net
      ip: 34.68.246.23

peer:
  enabled: false
  ### configmap
#  config:
#    peerAddress: "p0o1-hlf-peer:7051"
#    peerTlsRootcertFile: /var/hyperledger/crypto-config/Org1MSP/peer0.org1.net/tls-msp/signcerts/cert.pem
  ### certs provider by org0, to peer
#  secret:
#    ordTlsSignCert: orderer0.org0.com-tlssigncert
#    ordTlsCaCert: org0-tls-ca-cert

persistence:
  # alway enabled
  enabled: true
  pvcName: pvc-org0
#  annotations: {}
#  accessMode: ReadWriteOnce
#  # hostPath for PV for "manual" storageClass. If no storageClass, hostPath can omit
#  hostPath: /tmp/data/org0
#  # pv is requred for "manual" storageClass. If no storageClass, pv can omit
#  pvName: pv-org0
#  # mandatory
#  # storageClass can be "-", manual, or storageClass is not required for dynamic provisioning
#  # storageClass: "-"
#  # storageClass: manual
#  # requested size for pv
#  size: 1Gi

# Detail configuration
# https://github:com/bitnami/charts/tree/master/bitnami/postgresql
postgresql-0:
  postgresqlPassword: password
  initdbScripts:
    1-createdb.sql: |
      CREATE DATABASE "tls_ca_db";
      CREATE DATABASE "rca_db";
  service:
    type: NodePort
    nodePort: 30432
  persistence:
    enabled: true
    existingClaim: pvc-org0
    subPath: pgdata
#    # storageClass: manual
#    accessModes:
#      - ReadWriteOnce
#    size: 1Gi
