global:
  TZ: Asia/Hong_Kong

mspId: Org0MSP

persistence:
  enabled: true
  # Persistence Volume Name for manual storage class
  pvName: pv-org0
  pvcName: pvc-org0
  hostPath: /tmp/data/org0

  ## A manually managed Persistent Volume and Claim
  ## If defined, PVC must be created manually before volume will be bound
  subPath: ""

  # storageClass: "-"
  storageClass: manual
  accessMode: ReadWriteMany
  size: 10Mi
  annotations: {}

ordererConfiguration:
  enabled: true
  ORDERER_GENERAL_LOCALMSPID: Org0MSP
  org1cacert: "org1-cacerts"

postgresql-0:
  postgresqlPassword: password
  initdbScripts:
    1-createdb.sql: |
      CREATE DATABASE "tls_ca_db";
      CREATE DATABASE "rca_db";
  service:
    type: NodePort
    nodePort: 30432
  persistence:
    enabled: true
    existingClaim: pvc-org0
    subPath: pgdata
    storageClass: manual
    accessModes:
      - ReadWriteOnce
    size: 10Mi

cli:
  image:
    repository: hyperledger/fabric-tools
    tag: 2.1.0
    pullPolicy: IfNotPresent
  persistence:
    subPath: cli
    enabled: true
    size: 10Mi
