version: '2'

networks:
  openplatform:

services:
# ORG3
  gw-org3:
    image: fabric-es/gw-org3:1.0
    container_name: gw-org3
    environment:
      - AUTHORIZATION_SERVER_URI=http://auth-server3/oauth/authenticate
      - CA_ENROLLMENT_ID_ADMIN=rca-org3-admin
      - CA_ENROLLMENT_SECRET_ADMIN=rca-org3-adminPW
      - CHANNEL_HUB=peer0-org3
      - CONNECTION_PROFILE=/home/app/packages/gw-org3/connection/connection-org3.docker.yaml
      - COLLECTION=org3PrivateDetails
      - ORG_ADMIN_ID=admin-org3.net
      - ORG_ADMIN_SECRET=mEN6bpQW
      - ORG_CA_URL=https://rca-org3:5056
      - PEER_NAME=peer0-org3
      - GATEWAY_HOST=0.0.0.0
    working_dir: /home/app/packages/gw-org3
    ports:
      - 4013:4003
    networks:
      - openplatform
    depends_on:
      - auth-server3
      - orderer0-org0
      - peer0-org3
    volumes:
      - $VOLUME/gw-org3/assets/:/home/app/packages/gw-org3/assets/
      - $VOLUME/gw-org3/logs/:/home/app/packages/gw-org3/logs/
      - $ARTIFACTS/crypto-config/:/var/artifacts/crypto-config/
