version: '2'

networks:
  openplatform:

services:
  tls-ca-org0:
    extends:
      file: compose.1.3org.yaml
      service: tls-ca-org0
  rca-org0:
    extends:
      file: compose.1.3org.yaml
      service: rca-org0
  rca-org1:
    extends:
      file: compose.1.3org.yaml
      service: rca-org1
  rca-org2:
    extends:
      file: compose.1.3org.yaml
      service: rca-org2
  rca-org3:
    extends:
      file: compose.1.3org.yaml
      service: rca-org3
  peer0-org1:
    extends:
      file: compose.1.3org.yaml
      service: peer0-org1
  peer0-org2:
    extends:
      file: compose.1.3org.yaml
      service: peer0-org2
  peer0-org3:
    extends:
      file: compose.1.3org.yaml
      service: peer0-org3
  orderer0-org0:
    extends:
      file: compose.1.3org.yaml
      service: orderer0-org0
  cli:
    extends:
      file: compose.1.3org.yaml
      service: cli
  postgres01:
    extends:
      file: compose.1.3org.yaml
      service: postgres01
  postgres02:
    extends:
      file: compose.1.3org.yaml
      service: postgres02
  postgres03:
    extends:
      file: compose.1.3org.yaml
      service: postgres03

  auth-server1:
    image: fabric-es/auth-server:1.0
    container_name: auth-server1
    environment:
      - TYPEORM_HOST=postgres01
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
    ports:
      - 3901:8080
    depends_on:
      - postgres01
    volumes:
      - $VOLUME/auth-server1/logs/:/home/app/packages/authentication/logs/
    networks:
      - openplatform

  auth-server2:
    image: fabric-es/auth-server:1.0
    container_name: auth-server2
    environment:
      - TYPEORM_HOST=postgres02
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
    ports:
      - 3902:8080
    depends_on:
      - postgres02
    volumes:
      - $VOLUME/auth-server2/logs/:/home/app/packages/authentication/logs/
    networks:
      - openplatform

  auth-server3:
    image: fabric-es/auth-server:1.0
    container_name: auth-server3
    environment:
      - TYPEORM_HOST=postgres03
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
    ports:
      - 3903:8080
    depends_on:
      - postgres03
    volumes:
      - $VOLUME/auth-server3/logs/:/home/app/packages/authentication/logs/
    networks:
      - openplatform

  gw-org1:
    image: fabric-es/gw-org1:1.0
    container_name: gw-org1
    environment:
      - AUTHORIZATION_SERVER_URI=http://auth-server1/oauth/authenticate
      - CA_ENROLLMENT_ID_ADMIN=rca-org1-admin
      - CA_ENROLLMENT_SECRET_ADMIN=rca-org1-adminPW
      - CHANNEL_HUB=peer0-org1
      - CONNECTION_PROFILE=/home/app/packages/gw-org1/connection/connection-org1.docker.yaml
      - COLLECTION=org1PrivateDetails
      - ORG_ADMIN_ID=admin-org1.net
      - ORG_ADMIN_SECRET=Heym2rQK
      - ORG_CA_URL=https://rca-org1:5054
      - PEER_NAME=peer0-org1
      - GATEWAY_HOST=0.0.0.0
    working_dir: /home/app/packages/gw-org1
    ports:
      - 4011:4001
    networks:
      - openplatform
    depends_on:
      - auth-server1
      - orderer0-org0
      - peer0-org1
    volumes:
      - $VOLUME/gw-org1/assets/:/home/app/packages/gw-org1/assets/
      - $VOLUME/gw-org1/logs/:/home/app/packages/gw-org1/logs/
      - $ARTIFACTS/crypto-config/:/var/artifacts/crypto-config/

  gw-org2:
    image: fabric-es/gw-org2:1.0
    container_name: gw-org2
    environment:
      - AUTHORIZATION_SERVER_URI=http://auth-server2/oauth/authenticate
      - CA_ENROLLMENT_ID_ADMIN=rca-org2-admin
      - CA_ENROLLMENT_SECRET_ADMIN=rca-org2-adminPW
      - CHANNEL_HUB=peer0-org2
      - CONNECTION_PROFILE=/home/app/packages/gw-org2/connection/connection-org2.docker.yaml
      - COLLECTION=org2PrivateDetails
      - ORG_ADMIN_ID=admin-org2.net
      - ORG_ADMIN_SECRET=mEN6bpQW
      - ORG_CA_URL=https://rca-org2:5055
      - PEER_NAME=peer0-org2
      - GATEWAY_HOST=0.0.0.0
    working_dir: /home/app/packages/gw-org2
    ports:
      - 4012:4002
    networks:
      - openplatform
    depends_on:
      - auth-server2
      - orderer0-org0
      - peer0-org2
    volumes:
      - $VOLUME/gw-org2/assets/:/home/app/packages/gw-org2/assets/
      - $VOLUME/gw-org2/logs/:/home/app/packages/gw-org2/logs/
      - $ARTIFACTS/crypto-config/:/var/artifacts/crypto-config/

  gw-org3:
    image: fabric-es/gw-org3:1.0
    container_name: gw-org3
    environment:
      - AUTHORIZATION_SERVER_URI=http://auth-server3/oauth/authenticate
      - CA_ENROLLMENT_ID_ADMIN=rca-org3-admin
      - CA_ENROLLMENT_SECRET_ADMIN=rca-org3-adminPW
      - CHANNEL_HUB=peer0-org3
      - CONNECTION_PROFILE=/home/app/packages/gw-org3/connection/connection-org3.docker.yaml
      - COLLECTION=org3PrivateDetails
      - ORG_ADMIN_ID=admin-org3.net
      - ORG_ADMIN_SECRET=mEN6bpQW
      - ORG_CA_URL=https://rca-org3:5056
      - PEER_NAME=peer0-org3
      - GATEWAY_HOST=0.0.0.0
    working_dir: /home/app/packages/gw-org3
    ports:
      - 4013:4003
    networks:
      - openplatform
    depends_on:
      - auth-server3
      - orderer0-org0
      - peer0-org3
    volumes:
      - $VOLUME/gw-org3/assets/:/home/app/packages/gw-org3/assets/
      - $VOLUME/gw-org3/logs/:/home/app/packages/gw-org3/logs/
      - $ARTIFACTS/crypto-config/:/var/artifacts/crypto-config/

  tester:
    image: fabric-es/tester:1.0
    container_name: tester
    working_dir: /home/app/packages/tester
    networks:
      - openplatform
    command: ["jest", "integration.test"]
