version: '2'

networks:
  openplatform:

services:
  tester:
    image: fabric-es/tester:1.0
    container_name: tester
    working_dir: /home/app/packages/tester
    networks:
      - openplatform
    command: ["jest", "integration.test"]
