version: '2'

networks:
  openplatform:

services:
  tls-ca-org0:
    extends:
      file: compose.1.3org.yaml
      service: tls-ca-org0
  rca-org0:
    extends:
      file: compose.1.3org.yaml
      service: rca-org0
  rca-org1:
    extends:
      file: compose.1.3org.yaml
      service: rca-org1
  rca-org2:
    extends:
      file: compose.1.3org.yaml
      service: rca-org2
  rca-org3:
    extends:
      file: compose.1.3org.yaml
      service: rca-org3
  peer0-org1:
    extends:
      file: compose.1.3org.yaml
      service: peer0-org1
  peer0-org2:
    extends:
      file: compose.1.3org.yaml
      service: peer0-org2
  peer0-org3:
    extends:
      file: compose.1.3org.yaml
      service: peer0-org3
  orderer0-org0:
    extends:
      file: compose.1.3org.yaml
      service: orderer0-org0
  cli:
    extends:
      file: compose.1.3org.yaml
      service: cli

  postgres01:
    extends:
      file: compose.1.3org.yaml
      service: postgres01

  postgres02:
    extends:
      file: compose.1.3org.yaml
      service: postgres02

  postgres03:
    extends:
      file: compose.1.3org.yaml
      service: postgres03

  auth-server1:
    image: fabric-es/auth-server:1.0
    container_name: auth-server1
    environment:
      - TYPEORM_HOST=postgres01
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
    ports:
      - 3901:8080
    depends_on:
      - postgres01
    volumes:
      - $VOLUME/auth-server1/logs/:/home/app/packages/authentication/logs/
    networks:
      - openplatform

  auth-server2:
    image: fabric-es/auth-server:1.0
    container_name: auth-server2
    environment:
      - TYPEORM_HOST=postgres02
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
    ports:
      - 3902:8080
    depends_on:
      - postgres02
    volumes:
      - $VOLUME/auth-server2/logs/:/home/app/packages/authentication/logs/
    networks:
      - openplatform

  auth-server3:
    image: fabric-es/auth-server:1.0
    container_name: auth-server3
    environment:
      - TYPEORM_HOST=postgres03
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
    ports:
      - 3903:8080
    depends_on:
      - postgres03
    volumes:
      - $VOLUME/auth-server3/logs/:/home/app/packages/authentication/logs/
    networks:
      - openplatform
