export const lowerCasing: (value: string) => string = (value) =>
  value
    ? value
        .toLowerCase()
        .replace(/-/g, '_')
        .replace(/:/g, '_')
        .replace(/;/g, '_')
        .replace(/&/g, '_')
        .replace(/#/g, '_')
        .replace(/!/g, '_')
        .replace(/\s/g, '_')
        .replace(/\*/g, '_')
        .replace(/@/g, '_')
        .replace(/%/g, '_')
        .replace(/</g, '_')
        .replace(/>/g, '_')
        .replace(/\?/g, '_')
        .replace(/'/g, '_')
        .replace(/"/g, '_')
        .replace(/`/g, '_')
        .replace(/\[/g, '_')
        .replace(/]/g, '_')
        .replace(/{/g, '_')
        .replace(/}/g, '_')
        .replace(/\+/g, '_')
        .replace(/=/g, '_')
        .replace(/\(/g, '_')
        .replace(/\)/g, '_')
        .replace(/,/g, '_')
        .replace(/./g, '_')
        .replace(/\|/g, '_')
    : '';
