[ [ { version: 0,
  timestamp: null,
  response: [Object],
  payload: <Buffer >,
  endorsement: null,
  peer: [Object] },
  { version: 0,
    timestamp: null,
    response: [Object],
    payload: <Buffer >,
    endorsement: null,
    peer: [Object] } ],
  [ { version: 0,
    timestamp: null,
    response: [Object],
    payload: <Buffer >,
    endorsement: null,
    peer: [Object] },
    { version: 0,
      timestamp: null,
      response: [Object],
      payload: <Buffer >,
      endorsement: null,
      peer: [Object] } ] ]
