version: '2'

networks:
    middle-tier:

services:

    auth-server1:
        container_name: auth-server1
        image: hktfp5/auth-server
        environment:
            - TYPEORM_HOST=postgres01
            - TYPEORM_PORT=5432
            - TYPEORM_USERNAME=postgres
            - TYPEORM_PASSWORD=docker
            - TYPEORM_LOGGING=true
            - TYPEORM_DATABASE=auth_db
            - ROOT_ADMIN=root_admin1
            - ROOT_ADMIN_PASSWORD=root_admin1_password
        ports:
            - 3001:8080
        volumes:
            - ../data/auth-server1/logs/:/home/app/packages/authentication/logs/
        networks:
            - middle-tier

    auth-server2:
        container_name: auth-server2
        image: hktfp5/auth-server
        environment:
            - TYPEORM_HOST=postgres02
            - TYPEORM_PORT=5432
            - TYPEORM_USERNAME=postgres
            - TYPEORM_PASSWORD=docker
            - TYPEORM_LOGGING=true
            - TYPEORM_DATABASE=auth_db
            - ROOT_ADMIN=root_admin2
            - ROOT_ADMIN_PASSWORD=root_admin2_password
        ports:
            - 3002:8080
        volumes:
            - ../data/auth-server2/logs/:/home/app/packages/authentication/logs/
        networks:
            - middle-tier

    auth-server3:
        container_name: auth-server3
        image: hktfp5/auth-server
        environment:
            - TYPEORM_HOST=postgres03
            - TYPEORM_PORT=5432
            - TYPEORM_USERNAME=postgres
            - TYPEORM_PASSWORD=docker
            - TYPEORM_LOGGING=true
            - TYPEORM_DATABASE=auth_db
            - ROOT_ADMIN=root_admin3
            - ROOT_ADMIN_PASSWORD=root_admin3_password
        ports:
            - 3003:8080
        volumes:
            - ../data/auth-server3/logs/:/home/app/packages/authentication/logs/
        networks:
            - middle-tier

