version: '2'

networks:
    middle-tier:

services:

    postgres01:
        container_name: postgres01
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
        volumes:
            - ../data/postgres01:/var/lib/postgresql/data
            - ../sql/createdb.sql:/docker-entrypoint-initdb.d/1-createdb.sql
        networks:
            - middle-tier

    postgres02:
        container_name: postgres02
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
        volumes:
            - ../data/postgres02:/var/lib/postgresql/data
            - ../sql/createdb.sql:/docker-entrypoint-initdb.d/1-createdb.sql
        networks:
            - middle-tier

    postgres03:
        container_name: postgres03
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
        volumes:
            - ../data/postgres03:/var/lib/postgresql/data
            - ../sql/createdb.sql:/docker-entrypoint-initdb.d/1-createdb.sql
        networks:
            - middle-tier
