pipeline {

    environment {
        registryCredential = 'docker-registry-login'
        registryUrl = 'https://build:5000'
        nodeImage = 'build:5000/node8-build'

        yarnInstall = 'yarn install --ignore-engines'
        yarnBuild = 'yarn build:auth'

        imgName = 'build:5000/auth-server:${env.BUILD_TAG}'

        dockerhubCredential = 'dockerhub-login'
        imgNameHub = 'hktfp5/auth-server:${env.BUILD_TAG}'
    }

    agent none

    stages {
        stage('Yarn Build') {
            agent {
                docker {
                    image nodeImage
                    args '-p 3000:3000'
                    registryUrl registryUrl
                    registryCredentialsId registryCredential
                }
            }
            steps {
                sh yarnInstall
                sh 'docker build -t ${imgName} -f auth-server.dockerfile .'
            }
        }
        stage('Docker Build') {
            agent { label 'master' }
            steps {
                sh dockerBuild
            }
        }
        stage('Docker Push') {
            agent { label 'master' }
            steps {
                withCredentials([usernamePassword(credentialsId: registryCredential, passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
                    sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword} build:5000"
                    sh "docker push ${imgName}"
                }
            }
        }
        stage('Dockerhub Push') {
            agent { label 'master' }
            steps {
                sh 'docker tag ${imgName} ${imgNameHub}'
                withCredentials([usernamePassword(credentialsId: dockerhubCredential, passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
                    sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                    sh "docker push ${imgNameHub}"
                }
            }
        }
    }
}