global:
  TZ: Asia/Hong_Kong
  FABRIC_CFG_PATH: /etc/hyperledger/fabric/

ordererConfiguration:
  ORDERER_GENERAL_LOCALMSPID: Org0MSP

postgresql-0:
  postgresqlPassword: password
  initdbScripts:
    1-createdb.sql: |
      CREATE DATABASE "tls_ca_db";
      CREATE DATABASE "rca_db";
  persistence:
    enabled: true
    existingClaim: fabric-pvc-org0
    subPath: pgdata
    storageClass: manual
    accessModes:
      - ReadWriteOnce
    size: 10Mi

#postgresql-1:
#  postgresqlDatabase: fabric_ca
#  postgresqlPassword: password
#  initdbScripts:
#    1-createdb.sql: |
#      CREATE DATABASE "auth_db";
#  persistence:
#    enabled: true
#    existingClaim: fabric-pvc-rca0
#    subPath: pgdata
#    storageClass: manual
#    accessModes:
#      - ReadWriteOnce
#    size: 10Mi

tls-ca-org0:
  service:
    type: ClusterIP
    port: 7054
  adminUsername: tls-ca-admin
  adminPassword: tls-ca-adminPW
  caName: tls-ca-org0
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/rewrite-target: /
    hosts:
      - tls-ca-org0.local
  db:
    ssl: disable
  externalDatabase:
    type: postgres
    host: fdi-postgresql-0
    port: 5432
    database: tls_ca_db
    username: postgres
    password: password
  persistence:
    enabled: true
    storageClass: manual
    accessMode: ReadWriteOnce
    existingClaim: fabric-pvc-org0
    size: 10Mi
  config:
    hlfToolsVersion: 1.4.7
    fabricCaHome: /var/hyperledger/crypto-config/Org0MSP/tls/server
    fabricCaClientHome: /var/hyperledger/crypto-config/Org0MSP/tls/admin
    fabricCaClientTlsCertfiles: /var/hyperledger/crypto-config/Org0MSP/tls/server/ca-cert.pem
    csr:
      names:
        c: CN
        st: "Hong Kong"
        o: Fdi
        ou: Org0
  image:
    tag: 1.4.7

rca-org0:
  service:
    type: ClusterIP
    port: 7054
  adminUsername: rca-org0-admin
  adminPassword: rca-org0-adminPW
  caName: rca-org0
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/rewrite-target: /
    hosts:
      - rca-org0.local
  db:
    ssl: disable
  externalDatabase:
    type: postgres
    host: fdi-postgresql-0
    port: 5432
    database: rca_db
    username: postgres
    password: password
  persistence:
    enabled: true
    storageClass: manual
    accessMode: ReadWriteOnce
    existingClaim: fabric-pvc-org0
    size: 10Mi
  config:
    hlfToolsVersion: 1.4.7
    fabricCaHome: /var/hyperledger/crypto-config/Org0MSP/ca/server
    fabricCaClientHome: /var/hyperledger/crypto-config/Org0MSP/ca/admin
    fabricCaClientTlsCertfiles: /var/hyperledger/crypto-config/Org0MSP/ca/server/ca-cert.pem
    csr:
      names:
        c: CN
        st: "Hong Kong"
        o: Fdi
        ou: Org0
  image:
    tag: 1.4.7

cli:
  image:
    repository: hyperledger/fabric-tools
    tag: 2.1.0
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 10Mi
