version: '2'

networks:
  mynetwork:

services:
  explorer.mynetwork.com:
    container_name: explorer
    image: hyperledger/explorer
    environment:
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - /Users/tangross/dev/2019/open-platform-dlt/network/hosts:/tmp/crypto
    networks:
      - mynetwork
