apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hlf-ca.fullname" . }}--ca
  labels:
{{- include "labels.standard" . | nindent 4 }}
data:
  FABRIC_LOGGING_SPEC: {{ .Values.global.logging }}
  FABRIC_CA_HOME: {{ .Values.config.caServerHome | quote }}
  FABRIC_CA_SERVER_CA_NAME: {{ .Values.global.caName | quote }}
  SERVICE_DNS: 0.0.0.0  # Point to itself
  TZ: {{ .Values.global.TZ }}
  FABRIC_CA_CLIENT_HOME: {{ .Values.config.caClientHome | quote }}
