apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-ca.fullname" . }}
  labels:
{{- include "labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7054
      protocol: TCP
      name: http
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "hlf-ca.name" . }}
    release: {{ .Release.Name }}
