global:
  TZ: Asia/Hong_Kong
  mspId: Org0MSP
  workingDir: /var/hyperledger/crypto-config
  logging: info
  caName: org1-ca

caAdmin: admin
caAdminPW: adminPW

image:
  repository: hyperledger/fabric-ca
  tag: 1.4.7
  pullPolicy: IfNotPresent

service:
  ## Cluster IP or LoadBalancer
  type: ClusterIP
  port: 7054

## Settings used in configMap "--config"
config:
  ### Mandatory; no default
  caServerHome: /var/hyperledger/crypto-config/Org0MSP/fabric-ca
  caClientHome: /var/hyperledger/crypto-config/Org0MSP/client
  ### Enable debug logging in ca Server configuration file, in ca.yaml
  debug: false
  caClientTlsCertfiles: /var/hyperledger/crypto-config/Org0MSP/fabric-ca/ca-cert.pem
  ## Mount the TLS certificate & key to disk?
  mountTLS: false
  ## CSR pathlength in ca Server configuration file
  csr:
    ca:
      pathlength: 1
    names:
      c: US
      st: "North Carolina"
      o: Hyperledger
      ou: Fabric
      l:
  ### "intermediate" is only specified for Intermediate CA's
  # intermediate:
  #   parent:
  #     chart: parent-ca
  #     url: parent-ca.example.com
  #     port: 7054
  ### Affiliations used in ca Server configuration file, in ca.yaml
  # org1: []

### Not decided if it requires external network for CA
### Ingress is not properly implemented
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
  path: /
  hosts:
    - tlsca0
  tls: []
    # secretName is {{ Release.Name }}-tls. For org0, it must be tlsca0-tls
#    - secretName: "tlsca0-tls"
#      hosts:
#        - tlsca0

persistence:
  # Always true
  enabled: true
  existingClaim: pvc-org0

##################################
## Further configuration options #
##################################
db:
  # SSL authentication
  # Supported values are: "disable", "require", "verify-ca" and "verify-full".
  # https://github.com/hyperledger/fabric-ca/blob/master/docs/source/users-guide.rst
  ssl: disable

##
## External Database configuration (MySQL or PostgresSQL installed on/off Kubernetes)
##
externalDatabase:
  type: postgres
  host: admin0-postgresql-0
  port: 5432
  database: tls_ca_db
  username: postgres
  password: password

resources: {}
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
  ## Suggested antiAffinity, as each CA should be on a separate Node for resilience
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     - topologyKey: "kubernetes.io/hostname"
  #       labelSelector:
#         matchLabels:
#           app: hlf-ca
