################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

   - &org0
      Name: org0
      ID: org0MSP
      MSPDir: ../artifacts/crypto-config/org0/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('org0MSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('org0MSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('org0MSP.admin')"

   - &org1
      Name: org1
      ID: org1MSP
      MSPDir: ../artifacts/crypto-config/org1/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('org1MSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('org1MSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('org1MSP.admin')"

      OrdererEndpoints:
         - orderer1-org0:7050
         - orderer2-org0:7150
         - orderer3-org0:7250
         - orderer4-org0:7350
         - orderer5-org0:7450

      AnchorPeers:
         - Host: peer1-org1
           Port: 7051

   - &org2
      Name: org2
      ID: org2MSP
      MSPDir: ../artifacts/crypto-config/org2/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('org2MSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('org2MSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('org2MSP.admin')"

      OrdererEndpoints:
         - orderer1-org0:7050
         - orderer2-org0:7150
         - orderer3-org0:7250
         - orderer4-org0:7350
         - orderer5-org0:7450

      AnchorPeers:
         - Host: peer1-org2
           Port: 7251

Capabilities:
   Channel: &ChannelCapabilities
      V1_4_3: true
      V1_3: false
      V1_1: false
   Orderer: &OrdererCapabilities
      V1_4_2: true
      V1_1: false
   Application: &ApplicationCapabilities
      V1_4_2: true
      V1_3: false
      V1_2: false
      V1_1: false

################################################################################
#
#   SECTION: Application
#
#   This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

   # Organizations is the list of orgs which are defined as participants on
   # the application side of the network
   Organizations:
   Policies:
      Readers:
         Type: ImplicitMeta
         Rule: "ANY Readers"
      Writers:
         Type: ImplicitMeta
         Rule: "ANY Writers"
      Admins:
         Type: ImplicitMeta
         Rule: "MAJORITY Admins"

   Capabilities:
      <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

   OrdererType: etcdraft
   Addresses:
      - orderer1-org0:7050
      - orderer2-org0:7150
      - orderer3-org0:7250
      - orderer4-org0:7350
      - orderer5-org0:7450
   BatchTimeout: 2s
   BatchSize:
      MaxMessageCount: 500
      AbsoluteMaxBytes: 99 MB
      PreferredMaxBytes: 2 MB
   MaxChannels: 10
   EtcdRaft:
      Consenters:
         - Host: orderer1-org0
           Port: 7050
           ClientTLSCert: ../artifacts/crypto-config/org0/orderer1/tls-msp/signcerts/cert.pem
           ServerTLSCert: ../artifacts/crypto-config/org0/orderer1/tls-msp/signcerts/cert.pem
         - Host: orderer2-org0
           Port: 7150
           ClientTLSCert: ../artifacts/crypto-config/org0/orderer2/tls-msp/signcerts/cert.pem
           ServerTLSCert: ../artifacts/crypto-config/org0/orderer2/tls-msp/signcerts/cert.pem
         - Host: orderer3-org0
           Port: 7250
           ClientTLSCert: ../artifacts/crypto-config/org0/orderer3/tls-msp/signcerts/cert.pem
           ServerTLSCert: ../artifacts/crypto-config/org0/orderer3/tls-msp/signcerts/cert.pem
         - Host: orderer4-org0
           Port: 7350
           ClientTLSCert: ../artifacts/crypto-config/org0/orderer4/tls-msp/signcerts/cert.pem
           ServerTLSCert: ../artifacts/crypto-config/org0/orderer4/tls-msp/signcerts/cert.pem
         - Host: orderer5-org0
           Port: 7450
           ClientTLSCert: ../artifacts/crypto-config/org0/orderer5/tls-msp/signcerts/cert.pem
           ServerTLSCert: ../artifacts/crypto-config/org0/orderer5/tls-msp/signcerts/cert.pem

      Options:
         TickInterval: 500ms
         ElectionTick: 10
         HeartbeatTick: 1
         MaxInflightBlocks: 5
         SnapshotIntervalSize: 20 MB

   Organizations:
   Policies:
      Readers:
         Type: ImplicitMeta
         Rule: "ANY Readers"
      Writers:
         Type: ImplicitMeta
         Rule: "ANY Writers"
      Admins:
         Type: ImplicitMeta
         Rule: "MAJORITY Admins"
      BlockValidation:
         Type: ImplicitMeta
         Rule: "ANY Writers"

Channel: &ChannelDefaults
   Policies:
      Readers:
         Type: ImplicitMeta
         Rule: "ANY Readers"
      Writers:
         Type: ImplicitMeta
         Rule: "ANY Writers"
      Admins:
         Type: ImplicitMeta
         Rule: "MAJORITY Admins"

   Capabilities:
      <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

   OrgsOrdererGenesis:
      <<: *ChannelDefaults
      Orderer:
         <<: *OrdererDefaults
         Organizations:
            - *org0
         Capabilities:
            <<: *OrdererCapabilities
      Consortiums:
         SampleConsortium:
            Organizations:
               - *org1
               - *org2

   OrgsChannel:
      Consortium: SampleConsortium
      <<: *ChannelDefaults
      Application:
         <<: *ApplicationDefaults
         Organizations:
            - *org1
            - *org2
         Capabilities:
            <<: *ApplicationCapabilities
