################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

   - &OrdererOrg
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: ../artifacts/example.com/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('OrdererMSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('OrdererMSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('OrdererMSP.admin')"

   - &Org1MSP
      Name: Org1MSP
      ID: Org1MSP
      MSPDir: ../artifacts/org1.example.com/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('Org1MSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('Org1MSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('Org1MSP.admin')"

      OrdererEndpoints:
         - orderer1.example.com:7050
         - orderer2.example.com:7150
         - orderer3.example.com:7250
         - orderer4.example.com:7350
         - orderer5.example.com:7450

      AnchorPeers:
         - Host: peer0.org1.example.com
           Port: 7051

   - &Org2MSP
      Name: Org2MSP
      ID: Org2MSP
      MSPDir: ../artifacts/org2.example.com/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('Org2MSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('Org2MSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('Org2MSP.admin')"

      OrdererEndpoints:
         - orderer1.example.com:7050
         - orderer2.example.com:7150
         - orderer3.example.com:7250
         - orderer4.example.com:7350
         - orderer5.example.com:7450

      AnchorPeers:
         - Host: peer0.org2.example.com
           Port: 9051

   - &Org3MSP
      Name: Org3MSP
      ID: Org3MSP
      MSPDir: ../artifacts/org3.neworg.com/msp

      Policies:
         Readers:
            Type: Signature
            Rule: "OR('Org3MSP.member')"
         Writers:
            Type: Signature
            Rule: "OR('Org3MSP.member')"
         Admins:
            Type: Signature
            Rule: "OR('Org3MSP.admin')"

      OrdererEndpoints:
         - orderer1.example.com:7050
         - orderer2.example.com:7150
         - orderer3.example.com:7250
         - orderer4.example.com:7350
         - orderer5.example.com:7450

      AnchorPeers:
         - Host: peer0.org3.neworg.com
           Port: 11051

Capabilities:
   Channel: &ChannelCapabilities
      V1_4_3: true
      V1_3: false
      V1_1: false
   Orderer: &OrdererCapabilities
      V1_4_2: true
      V1_1: false
   Application: &ApplicationCapabilities
      V1_4_2: true
      V1_3: false
      V1_2: false
      V1_1: false

################################################################################
#
#   SECTION: Application
#
#   This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

   # Organizations is the list of orgs which are defined as participants on
   # the application side of the network
   Organizations:
   Policies:
      Readers:
         Type: ImplicitMeta
         Rule: "ANY Readers"
      Writers:
         Type: ImplicitMeta
         Rule: "ANY Writers"
      Admins:
         Type: ImplicitMeta
         Rule: "MAJORITY Admins"

   Capabilities:
      <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

   OrdererType: etcdraft
   Addresses:
      - orderer1.example.com:7050
      - orderer2.example.com:7150
      - orderer3.example.com:7250
      - orderer4.example.com:7350
      - orderer5.example.com:7450
   BatchTimeout: 2s
   BatchSize:
      MaxMessageCount: 500
      AbsoluteMaxBytes: 99 MB
      PreferredMaxBytes: 2 MB
   MaxChannels: 10
   EtcdRaft:
      Consenters:
         - Host: orderer1.example.com
           Port: 7050
           ClientTLSCert: ../artifacts/example.com/orderer1/tls-msp/signcerts/cert.pem
           ServerTLSCert: ../artifacts/example.com/orderer1/tls-msp/signcerts/cert.pem
         - Host: orderer2.example.com
           Port: 7150
           ClientTLSCert: ../artifacts/example.com/orderer2/tls-msp/signcerts/cert.pem
           ServerTLSCert: ../artifacts/example.com/orderer2/tls-msp/signcerts/cert.pem
         - Host: orderer3.example.com
           Port: 7250
           ClientTLSCert: ../artifacts/example.com/orderer3/tls-msp/signcerts/cert.pem
           ServerTLSCert: ../artifacts/example.com/orderer3/tls-msp/signcerts/cert.pem
         - Host: orderer4.example.com
           Port: 7350
           ClientTLSCert: ../artifacts/example.com/orderer4/tls-msp/signcerts/cert.pem
           ServerTLSCert: ../artifacts/example.com/orderer4/tls-msp/signcerts/cert.pem
         - Host: orderer5.example.com
           Port: 7450
           ClientTLSCert: ../artifacts/example.com/orderer5/tls-msp/signcerts/cert.pem
           ServerTLSCert: ../artifacts/example.com/orderer5/tls-msp/signcerts/cert.pem

      Options:
         TickInterval: 500ms
         ElectionTick: 10
         HeartbeatTick: 1
         MaxInflightBlocks: 5
         SnapshotIntervalSize: 20 MB

   Organizations:
   Policies:
      Readers:
         Type: ImplicitMeta
         Rule: "ANY Readers"
      Writers:
         Type: ImplicitMeta
         Rule: "ANY Writers"
      Admins:
         Type: ImplicitMeta
         Rule: "MAJORITY Admins"
      BlockValidation:
         Type: ImplicitMeta
         Rule: "ANY Writers"

Channel: &ChannelDefaults
   Policies:
      Readers:
         Type: ImplicitMeta
         Rule: "ANY Readers"
      Writers:
         Type: ImplicitMeta
         Rule: "ANY Writers"
      Admins:
         Type: ImplicitMeta
         Rule: "MAJORITY Admins"

   Capabilities:
      <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

   OrgsOrdererGenesis:
      <<: *ChannelDefaults
      Orderer:
         <<: *OrdererDefaults
         Organizations:
            - *OrdererOrg
         Capabilities:
            <<: *OrdererCapabilities
      Consortiums:
         SampleConsortium:
            Organizations:
               - *Org1MSP
               - *Org2MSP
               - *Org3MSP

   OrgsChannel:
      Consortium: SampleConsortium
      <<: *ChannelDefaults
      Application:
         <<: *ApplicationDefaults
         Organizations:
            - *Org1MSP
            - *Org2MSP
            - *Org3MSP
         Capabilities:
            <<: *ApplicationCapabilities
