---
name: fdi_openplatform-all
version: 1.0.0

channels:
  eventstore:
    orderers:
      - orderer0-hktfp
    peers:
      peer0-etradeconnect:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1-etradeconnect:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0-pbctfp:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1-pbctfp:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0-hsbc:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1-hsbc:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
      - eventstore:1.0

organizations:
  EtcMSP:
    mspid: EtcMSP
    peers:
      - peer0-etradeconnect
      - peer1-etradeconnect
    certificateAuthorities:
      - rca-etradeconnect
    adminPrivateKey:
      path: ../../network2/config/../artifacts/crypto-config/EtcMSP/admin/msp/keystore/key.pem
    signedCert:
      path: ../../network2/config/../artifacts/crypto-config/EtcMSP/admin/msp/signcerts/cert.pem
  PbctfpMSP:
    mspid: PbctfpMSP
    peers:
      - peer0-pbctfp
      - peer1-pbctfp
    certificateAuthorities:
      - rca-pbctfp
    adminPrivateKey:
      path: ../../network2/config/../artifacts/crypto-config/PbctfpMSP/admin/msp/keystore/key.pem
    signedCert:
      path: ../../network2/config/../artifacts/crypto-config/PbctfpMSP/admin/msp/signcerts/cert.pem
  HsbcMSP:
    mspid: HsbcMSP
    peers:
      - peer0-hsbc
      - peer1-hsbc
    certificateAuthorities:
      - rca-hsbc
    adminPrivateKey:
      path: ../../network2/config/../artifacts/crypto-config/HsbcMSP/admin/msp/keystore/key.pem
    signedCert:
      path: ../../network2/config/../artifacts/crypto-config/HsbcMSP/admin/msp/signcerts/cert.pem

orderers:
  orderer0-hktfp:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer0-hktfp
    #      grpc-max-send-message-length: 4000
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/HktfpMSP/orderer0.hktfp.com/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem

peers:
  peer0-etradeconnect:
    url: grpcs://localhost:7051
    eventUrl: grpcs://localhost:7053
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/EtcMSP/peer0.etradeconnect.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer0-etradeconnect
  peer1-etradeconnect:
    url: grpcs://localhost:7151
    eventUrl: grpcs://localhost:7153
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/EtcMSP/peer1.etradeconnect.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer1-etradeconnect
  peer0-pbctfp:
    url: grpcs://localhost:7251
    eventUrl: grpcs://localhost:7253
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/PbctfpMSP/peer0.pbctfp.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer0-pbctfp
  peer1-pbctfp:
    url: grpcs://localhost:7351
    eventUrl: grpcs://localhost:7353
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/PbctfpMSP/peer1.pbctfp.net/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer1-pbctfp
  peer0-hsbc:
    url: grpcs://localhost:7451
    eventUrl: grpcs://localhost:7453
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/HsbcMSP/peer0.hsbc.com.hk/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer0-hsbc
  peer1-hsbc:
    url: grpcs://localhost:7551
    eventUrl: grpcs://localhost:7553
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/HsbcMSP/peer1.hsbc.com.hk/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
    grpcOptions:
      ssl-target-name-override: peer1-hsbc

certificateAuthorities:
  rca-etradeconnect:
    url: https://localhost:6054
    caName: rca-etradeconnect
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/EtcMSP/msp/tlscacerts/tls-ca-cert.pem
    registrar:
      - enrollId: rca-etradeconnect-admin
        enrollSecret: rca-etradeconnect-adminPW
    httpOptions:
      verify: false
    rca-pbctfp:
    url: https://localhost:6055
    caName: rca-pbctfp
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/PbctfpMSP/msp/tlscacerts/tls-ca-cert.pem
    registrar:
      - enrollId: rca-pboc-admin
        enrollSecret: rca-pboc-adminPW
    httpOptions:
      verify: false
    rca-hsbc:
    url: https://localhost:5054
    caName: rca-hsbc
    tlsCACerts:
      path: ../../network2/config/../artifacts/crypto-config/HsbcMSP/msp/tlscacerts/tls-ca-cert.pem
    registrar:
      - enrollId: rca-hsbc-admin
        enrollSecret: rca-hsbc-adminPW
    httpOptions:
      verify: false
  