---
name: openplatform_fabric-Org3MSP
version: 1.0.0

client:
  organization: Org3MSP
  credentialStore:
    path: ./assets/client-certs/hfc-kvs/org3.neworg.com
    cryptoStore:
      path: ./assets/client-certs/hfc-kvs/org3.neworg.com
  connection:
    timeout:
      peer:
        endorser: '300'

channels:
  eventstore:
    orderers:
      - orderer1.example.com
    peers:
      peer0.org3.neworg.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org3.neworg.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincodes:
      - eventstore:1.0

organizations:
  Org3MSP:
    mspid: Org3MSP
    peers:
      - peer0.org3.neworg.com
      - peer1.org3.neworg.com
    certificateAuthorities:
      - rca.org3.neworg.com
    adminPrivateKey:
      path: ../../network2/config/../artifacts/Org3MSP/admin/msp/keystore/key.pem
    signedCert:
      path: ../../network2/config/../artifacts/Org3MSP/admin/msp/signcerts/cert.pem

orderers:
  orderer1.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer1.example.com
    #      grpc-max-send-message-length: 4000
    tlsCACerts:
      path: ../../network2/config/../artifacts/OrdererMSP/orderer1.example.com/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem

peers:
  peer0.org3.neworg.com:
    url: grpcs://localhost:11051
    eventUrl: grpcs://localhost:11053
    tlsCACerts:
      path: ../../network2/config/../artifacts/Org3MSP/peer0.org3.neworg.com/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
    grpcOptions:
      ssl-target-name-override: peer0.org3.neworg.com
  peer1.org3.neworg.com:
    url: grpcs://localhost:12051
    eventUrl: grpcs://localhost:12053
    tlsCACerts:
      path: ../../network2/config/../artifacts/Org3MSP/peer1.org3.neworg.com/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
    grpcOptions:
      ssl-target-name-override: peer1.org3.neworg.com

certificateAuthorities:
  rca.org3.neworg.com:
    url: https://localhost:5056
    caName: rca.org3.neworg.com
    tlsCACerts:
      path: ../../network2/config/../artifacts/Org3MSP/msp/tlscacerts/tls-ca-cert.pem
    registrar:
      - enrollId: rca-org3-admin
        enrollSecret: rca-org3-adminPW
    httpOptions:
      verify: false
