version: '2'

networks:
    fabric:

services:

    ca.tls:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: ca.tls
        restart: always
        environment:
            - HYPERLEDGER_VOL=/tmp/hyperledger
            - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/ca.tls/crypto
            - FABRIC_CA_SERVER_CSR_CN=ca.tls
        ports:
            - 5052:5052
        command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminPW --cfg.affiliations.allowremove --cfg.identities.allowremove --port 5052'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/tmp/hyperledger

    rca.example.com:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: rca.example.com
        restart: always
        environment:
            - HYPERLEDGER_VOL=/tmp/hyperledger
            - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/rca.example.com/crypto
            - FABRIC_CA_SERVER_CSR_CN=rca.example.com
        ports:
            - 5053:5053
        command: sh -c 'fabric-ca-server start -d -b rca-org0-admin:rca-org0-adminPW --cfg.affiliations.allowremove --cfg.identities.allowremove --port 5053'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/tmp/hyperledger

    rca.org1.example.com:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: rca.org1.example.com
        restart: always
        environment:
            - HYPERLEDGER_VOL=/tmp/hyperledger
            - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/rca.org1.example.com/crypto
            - FABRIC_CA_SERVER_CSR_CN=rca.org1.example.com
        ports:
            - 5054:5054
        command: sh -c 'fabric-ca-server start -d -b rca-org1-admin:rca-org1-adminPW --cfg.affiliations.allowremove  --cfg.identities.allowremove --port 5054'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/tmp/hyperledger

    rca.org2.example.com:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: rca.org2.example.com
        restart: always
        environment:
            - HYPERLEDGER_VOL=/tmp/hyperledger
            - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/rca.org2.example.com/crypto
            - FABRIC_CA_SERVER_CSR_CN=rca.org2.example.com
        ports:
            - 5055:5055
        command: sh -c 'fabric-ca-server start -d -b rca-org2-admin:rca-org2-adminPW --cfg.affiliations.allowremove  --cfg.identities.allowremove --port 5055'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/tmp/hyperledger

    peer0.org1.example.com:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer0.org1.example.com
        environment:
            - CORE_PEER_ID=peer0.org1.example.com
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org1.example.com/peer0/msp
            - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org1.example.com/peer0/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org1.example.com/peer0/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org1.example.com/peer0/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1.example.com/peer0
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/org1.example.com/peer0:/tmp/hyperledger/production
            - ../artifacts/org1.example.com/peer0:/tmp/hyperledger/org1.example.com/peer0
        ports:
            - 7051:7051

    peer1.org1.example.com:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer1.org1.example.com
        environment:
            - CORE_PEER_ID=peer1.org1.example.com
            - CORE_PEER_ADDRESS=peer1.org1.example.com:8051
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org1.example.com/peer1/msp
            - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org1.example.com/peer1/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org1.example.com/peer1/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org1.example.com/peer1/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:8051
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1.example.com/peer1
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/org1.example.com/peer1:/tmp/hyperledger/production
            - ../artifacts/org1.example.com/peer1:/tmp/hyperledger/org1.example.com/peer1
        ports:
            - 8051:8051

    peer0.org2.example.com:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer0.org2.example.com
        environment:
            - CORE_PEER_ID=peer0.org2.example.com
            - CORE_PEER_ADDRESS=peer0.org2.example.com:9051
            - CORE_PEER_LOCALMSPID=org2MSP
            - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org2.example.com/peer0/msp
            - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org2.example.com/peer0/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org2.example.com/peer0/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org2.example.com/peer0/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:9051
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2.example.com/peer0
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/org2.example.com/peer0:/tmp/hyperledger/production
            - ../artifacts/org2.example.com/peer0:/tmp/hyperledger/org2.example.com/peer0
        ports:
            - 9051:9051

    peer1.org2.example.com:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer1.org2.example.com
        environment:
            - CORE_PEER_ID=peer1.org2.example.com
            - CORE_PEER_ADDRESS=peer1.org2.example.com:10051
            - CORE_PEER_LOCALMSPID=org2MSP
            - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org2.example.com/peer1/msp
            - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org2.example.com/peer1/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org2.example.com/peer1/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org2.example.com/peer1/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:10051
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2.example.com/peer1
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/org2.example.com/peer1:/tmp/hyperledger/production
            - ../artifacts/org2.example.com/peer1:/tmp/hyperledger/org2.example.com/peer1
        ports:
            - 10051:10051

    orderer1.example.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer1.example.com
        environment:
            - ORDERER_HOST=orderer1.example.com
            - ORDERER_HOME=/tmp/hyperledger/orderer
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/example.com/orderer1/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/example.com/orderer1/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/example.com/orderer1/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/example.com/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem]
            - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/example.com/orderer1/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/example.com/orderer1/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/example.com/orderer1/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/example.com/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem]
            - ORDERER_GENERAL_LISTENPORT=7050
        volumes:
            - ../artifacts/production/example.com/orderer1:/tmp/hyperledger/production
            - ../artifacts/example.com/orderer1:/tmp/hyperledger/example.com/orderer1
        ports:
            - 7050:7050

    orderer2.example.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer2.example.com
        environment:
            - ORDERER_HOST=orderer2.example.com
            - ORDERER_HOME=/tmp/hyperledger/orderer
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/example.com/orderer2/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/example.com/orderer2/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/example.com/orderer2/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/example.com/orderer2/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem]
            - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/example.com/orderer2/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/example.com/orderer2/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/example.com/orderer2/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/example.com/orderer2/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem]
            - ORDERER_GENERAL_LISTENPORT=7150
        volumes:
            - ../artifacts/production/example.com/orderer2:/tmp/hyperledger/production
            - ../artifacts/example.com/orderer2:/tmp/hyperledger/example.com/orderer2
        ports:
            - 7150:7150

    orderer3.example.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer3.example.com
        environment:
            - ORDERER_HOST=orderer3.example.com
            - ORDERER_HOME=/tmp/hyperledger/orderer
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/example.com/orderer3/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/example.com/orderer3/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/example.com/orderer3/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/example.com/orderer3/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem]
            - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/example.com/orderer3/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/example.com/orderer3/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/example.com/orderer3/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/example.com/orderer3/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem]
            - ORDERER_GENERAL_LISTENPORT=7250
        volumes:
            - ../artifacts/production/example.com/orderer3:/tmp/hyperledger/production
            - ../artifacts/example.com/orderer3:/tmp/hyperledger/example.com/orderer3
        ports:
            - 7250:7250

    orderer4.example.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer4.example.com
        environment:
            - ORDERER_HOST=orderer4.example.com
            - ORDERER_HOME=/tmp/hyperledger/orderer
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/example.com/orderer4/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/example.com/orderer4/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/example.com/orderer4/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/example.com/orderer4/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem]
            - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/example.com/orderer4/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/example.com/orderer4/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/example.com/orderer4/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/example.com/orderer4/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem]
            - ORDERER_GENERAL_LISTENPORT=7350
        volumes:
            - ../artifacts/production/example.com/orderer4:/tmp/hyperledger/production
            - ../artifacts/example.com/orderer4:/tmp/hyperledger/example.com/orderer4
        ports:
            - 7350:7350

    orderer5.example.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer5.example.com
        environment:
            - ORDERER_HOST=orderer5.example.com
            - ORDERER_HOME=/tmp/hyperledger/orderer
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/example.com/orderer5/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/example.com/orderer5/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/example.com/orderer5/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/example.com/orderer5/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem]
            - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/example.com/orderer5/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/example.com/orderer5/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/example.com/orderer5/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/example.com/orderer5/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem]
            - ORDERER_GENERAL_LISTENPORT=7450
        volumes:
            - ../artifacts/production/example.com/orderer5:/tmp/hyperledger/production
            - ../artifacts/example.com/orderer5:/tmp/hyperledger/example.com/orderer5
        ports:
            - 7450:7450

    cli.org1.example.com:
        extends:
            file: nodebase.yaml
            service: cli
        container_name: cli.org1.example.com
        environment:
            - HYPERLEDGER_VOL=/tmp/hyperledger
            - CORE_PEER_ID=cli.org1.example.com
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org1.example.com/peer0/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
            - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org1.example.com/peer0/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1.example.com
        command: sh
        volumes:
            - ../artifacts:/tmp/hyperledger
            - ../scripts/container:/setup
            - ../../packages/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode

    cli.org2.example.com:
        extends:
            file: nodebase.yaml
            service: cli
        container_name: cli.org2.example.com
        environment:
            - HYPERLEDGER_VOL=/tmp/hyperledger
            - CORE_PEER_ID=cli.org2.example.com
            - CORE_PEER_ADDRESS=peer0.org2.example.com:9051
            - CORE_PEER_LOCALMSPID=org2MSP
            - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org2.example.com/peer0/tls-msp/tlscacerts/tls-0-0-0-0-5052.pem
            - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org2.example.com/peer0/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2.example.com
        command: sh
        volumes:
            - ../artifacts:/tmp/hyperledger
            - ../scripts/container:/setup
            - ../../packages/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode

    postgres01:
        container_name: postgres01
        image: postgres
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_USER=postgres
            - POSTGRES_DB=account01
        volumes:
            - ../artifacts/postgres01:/var/lib/postgresql/data
        command: postgres
        ports:
            - 5432
        networks:
            - fabric
