version: '2'

networks:
    fabric:

services:

    ca-tls:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: ca-tls
        restart: always
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - FABRIC_CA_SERVER_HOME=/var/artifacts/crypto-config/ca-tls/server
            - FABRIC_CA_SERVER_CSR_CN=ca-tls
        ports:
            - 6052:6052
        command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminPW --cfg.affiliations.allowremove --cfg.identities.allowremove --port 6052'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/var/artifacts

    rca-org0:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: rca-org0
        restart: always
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - FABRIC_CA_SERVER_HOME=/var/artifacts/crypto-config/rca-org0/server
            - FABRIC_CA_SERVER_CSR_CN=rca-org0
        ports:
            - 6053:6053
        command: sh -c 'fabric-ca-server start -d -b rca-org0-admin:rca-org0-adminPW --cfg.affiliations.allowremove --cfg.identities.allowremove --port 6053'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/var/artifacts

    rca-org1:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: rca-org1
        restart: always
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - FABRIC_CA_SERVER_HOME=/var/artifacts/crypto-config/rca-org1/server
            - FABRIC_CA_SERVER_CSR_CN=rca-org1
        ports:
            - 6054:6054
        command: sh -c 'fabric-ca-server start -d -b rca-org1-admin:rca-org1-adminPW --cfg.affiliations.allowremove  --cfg.identities.allowremove --port 6054'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/var/artifacts

    rca-org2:
        extends:
            file: nodebase.yaml
            service: ca
        container_name: rca-org2
        restart: always
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - FABRIC_CA_SERVER_HOME=/var/artifacts/crypto-config/rca-org2/server
            - FABRIC_CA_SERVER_CSR_CN=rca-org2
        ports:
            - 6055:6055
        command: sh -c 'fabric-ca-server start -d -b rca-org2-admin:rca-org2-adminPW --cfg.affiliations.allowremove  --cfg.identities.allowremove --port 6055'
        volumes:
            - ../scripts/container:/setup
            - ../artifacts:/var/artifacts

    peer1-org1:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer1-org1
        environment:
            - CORE_PEER_ID=peer1-org1
            - CORE_PEER_ADDRESS=peer1-org1:7051
            - CORE_PEER_LOCALMSPID=org1MSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/org1/peer1/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/org1/peer1/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/org1/peer1/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/org1/peer1/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org1:7051
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer1
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/org1/peer1:/var/artifacts/production
            - ../artifacts/crypto-config/org1/peer1:/var/artifacts/crypto-config/org1/peer1
        ports:
            - 7051:7051

    peer2-org1:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer2-org1
        environment:
            - CORE_PEER_ID=peer2-org1
            - CORE_PEER_ADDRESS=peer2-org1:7151
            - CORE_PEER_LOCALMSPID=org1MSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/org1/peer2/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/org1/peer2/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/org1/peer2/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/org1/peer2/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org1:7151
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7152
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer2
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/org1/peer2:/var/artifacts/production
            - ../artifacts/crypto-config/org1/peer2:/var/artifacts/crypto-config/org1/peer2
        ports:
            - 7151:7151

    peer1-org2:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer1-org2
        environment:
            - CORE_PEER_ID=peer1-org2
            - CORE_PEER_ADDRESS=peer1-org2:7251
            - CORE_PEER_LOCALMSPID=org2MSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/org2/peer1/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/org2/peer1/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/org2/peer1/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/org2/peer1/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org2:7251
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7252
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2/peer1
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/org2/peer1:/var/artifacts/production
            - ../artifacts/crypto-config/org2/peer1:/var/artifacts/crypto-config/org2/peer1
        ports:
            - 7251:7251

    peer2-org2:
        extends:
            file: nodebase.yaml
            service: peer
        container_name: peer2-org2
        environment:
            - CORE_PEER_ID=peer2-org2
            - CORE_PEER_ADDRESS=peer2-org2:7351
            - CORE_PEER_LOCALMSPID=org2MSP
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/org2/peer2/msp
            - CORE_PEER_TLS_CERT_FILE=/var/artifacts/crypto-config/org2/peer2/tls-msp/signcerts/cert.pem
            - CORE_PEER_TLS_KEY_FILE=/var/artifacts/crypto-config/org2/peer2/tls-msp/keystore/key.pem
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/org2/peer2/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org2:7351
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7352
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2/peer2
        volumes:
            - /var/run:/host/var/run
            - ../artifacts/production/org2/peer2:/var/artifacts/production
            - ../artifacts/crypto-config/org2/peer2:/var/artifacts/crypto-config/org2/peer2
        ports:
            - 7351:7351

    orderer1-org0:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer1-org0
        environment:
            - ORDERER_HOST=orderer1-org0
            - ORDERER_HOME=/var/artifacts/orderer
            - ORDERER_GENERAL_LOCALMSPID=org0MSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/artifacts/crypto-config/org0/orderer1/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/artifacts/crypto-config/org0/orderer1/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/artifacts/crypto-config/org0/orderer1/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/artifacts/crypto-config/org0/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_GENESISFILE=/var/artifacts/crypto-config/org0/orderer1/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/artifacts/crypto-config/org0/orderer1/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/artifacts/crypto-config/org0/orderer1/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/artifacts/crypto-config/org0/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_LISTENPORT=7050
        volumes:
            - ../artifacts/production/org0/orderer1:/var/artifacts/production
            - ../artifacts/crypto-config/org0/orderer1:/var/artifacts/crypto-config/org0/orderer1
        ports:
            - 7050:7050

    orderer2-org0:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer2-org0
        environment:
            - ORDERER_HOST=orderer2-org0
            - ORDERER_HOME=/var/artifacts/orderer
            - ORDERER_GENERAL_LOCALMSPID=org0MSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/artifacts/crypto-config/org0/orderer2/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/artifacts/crypto-config/org0/orderer2/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/artifacts/crypto-config/org0/orderer2/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/artifacts/crypto-config/org0/orderer2/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_GENESISFILE=/var/artifacts/crypto-config/org0/orderer2/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/artifacts/crypto-config/org0/orderer2/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/artifacts/crypto-config/org0/orderer2/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/artifacts/crypto-config/org0/orderer2/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_LISTENPORT=7150
        volumes:
            - ../artifacts/production/org0/orderer2:/var/artifacts/production
            - ../artifacts/crypto-config/org0/orderer2:/var/artifacts/crypto-config/org0/orderer2
        ports:
            - 7150:7150

    orderer3-org0:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer3-org0
        environment:
            - ORDERER_HOST=orderer3-org0
            - ORDERER_HOME=/var/artifacts/orderer
            - ORDERER_GENERAL_LOCALMSPID=org0MSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/artifacts/crypto-config/org0/orderer3/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/artifacts/crypto-config/org0/orderer3/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/artifacts/crypto-config/org0/orderer3/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/artifacts/crypto-config/org0/orderer3/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_GENESISFILE=/var/artifacts/crypto-config/org0/orderer3/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/artifacts/crypto-config/org0/orderer3/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/artifacts/crypto-config/org0/orderer3/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/artifacts/crypto-config/org0/orderer3/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_LISTENPORT=7250
        volumes:
            - ../artifacts/production/org0/orderer3:/var/artifacts/production
            - ../artifacts/crypto-config/org0/orderer3:/var/artifacts/crypto-config/org0/orderer3
        ports:
            - 7250:7250

    orderer4-org0:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer4-org0
        environment:
            - ORDERER_HOST=orderer4-org0
            - ORDERER_HOME=/var/artifacts/orderer
            - ORDERER_GENERAL_LOCALMSPID=org0MSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/artifacts/crypto-config/org0/orderer4/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/artifacts/crypto-config/org0/orderer4/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/artifacts/crypto-config/org0/orderer4/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/artifacts/crypto-config/org0/orderer4/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_GENESISFILE=/var/artifacts/crypto-config/org0/orderer4/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/artifacts/crypto-config/org0/orderer4/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/artifacts/crypto-config/org0/orderer4/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/artifacts/crypto-config/org0/orderer4/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_LISTENPORT=7350
        volumes:
            - ../artifacts/production/org0/orderer4:/var/artifacts/production
            - ../artifacts/crypto-config/org0/orderer4:/var/artifacts/crypto-config/org0/orderer4
        ports:
            - 7350:7350

    orderer5-org0:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer5-org0
        environment:
            - ORDERER_HOST=orderer5-org0
            - ORDERER_HOME=/var/artifacts/orderer
            - ORDERER_GENERAL_LOCALMSPID=org0MSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/artifacts/crypto-config/org0/orderer5/msp
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/artifacts/crypto-config/org0/orderer5/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/artifacts/crypto-config/org0/orderer5/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/artifacts/crypto-config/org0/orderer5/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_GENESISFILE=/var/artifacts/crypto-config/org0/orderer5/genesis.block
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/artifacts/crypto-config/org0/orderer5/tls-msp/signcerts/cert.pem
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/artifacts/crypto-config/org0/orderer5/tls-msp/keystore/key.pem
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/artifacts/crypto-config/org0/orderer5/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem]
            - ORDERER_GENERAL_LISTENPORT=7450
        volumes:
            - ../artifacts/production/org0/orderer5:/var/artifacts/production
            - ../artifacts/crypto-config/org0/orderer5:/var/artifacts/crypto-config/org0/orderer5
        ports:
            - 7450:7450

    cli-org1:
        extends:
            file: nodebase.yaml
            service: cli
        container_name: cli-org1
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - CORE_PEER_ID=cli-org1
            - CORE_PEER_ADDRESS=peer1-org1:7051
            - CORE_PEER_LOCALMSPID=org1MSP
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/org1/peer1/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/org1/peer1/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1
        command: sh
        volumes:
            - ../artifacts:/var/artifacts
            - ../scripts/container:/setup
            - ../../packages/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode

    cli-org2:
        extends:
            file: nodebase.yaml
            service: cli
        container_name: cli-org2
        environment:
            - HYPERLEDGER_VOL=/var/artifacts
            - CORE_PEER_ID=cli-org2
            - CORE_PEER_ADDRESS=peer1-org2:7251
            - CORE_PEER_LOCALMSPID=org2MSP
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/artifacts/crypto-config/org2/peer1/tls-msp/tlscacerts/tls-0-0-0-0-6052.pem
            - CORE_PEER_MSPCONFIGPATH=/var/artifacts/crypto-config/org2/peer1/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2
        command: sh
        volumes:
            - ../artifacts:/var/artifacts
            - ../scripts/container:/setup
            - ../../packages/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode

    postgres01:
        container_name: postgres01
        image: postgres
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_USER=postgres
            - POSTGRES_DB=account01
        volumes:
            - ../artifacts/postgres01:/var/lib/postgresql/data
        command: postgres
        ports:
            - 5432
        networks:
            - fabric
