{{- if .Values.joinChannel.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hlf-operator.fullname" . }}--joinchannel
  labels:
{{- include "labels.standard" . | nindent 4 }}
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: {{ .Values.joinChannel.orgadmin.pvcName }}
        - name: upload
          persistentVolumeClaim:
            claimName: {{ .Values.joinChannel.gupload.pvcName }}
        - name: setup-script
          configMap:
            name: {{ .Values.global.config.setupsh }}
            defaultMode: 0777
        - name: core-yaml
          configMap:
            name: {{ .Values.global.config.coreyaml }}
        - name: org0-tls-ca-cert
          secret:
            secretName: {{ .Values.joinChannel.secret.tlscacert }}
      containers:
        - name: updatechannel
          image: library/alpine:3.12.0
          command: ["sh", "-c"]
          workingDir: /var/hyperledger
          args:
            - |-
              . /script/setup.sh
              apk update
              apk upgrade
              apk --no-cache add libc6-compat libstdc++
              $BIN/peer version
              ########
              # Step 1: fetch block 0
              ########
              export TMP={{ .Values.global.workingDir }}/uploaded/tmp/{{include "hlf-operator.fullname" .}}
              printHeader "Fetch block 0"
              set -x
              rm -r $TMP
              mkdir -p $TMP
              $BIN/peer channel fetch 0 $TMP/${CHANNEL_NAME}.block \
                -c $CHANNEL_NAME -o ${ORDERER_URL} --tls --cafile ${ORDERER_CA} >& $TMP/log-fetch0.txt
              res=$?
              set +x
              printMessage "fetch block 0" $res
              cat $TMP/log-fetch0.txt
              ########
              # Step 2: join channel
              ########
              printHeader "Join channel"
              set -x
              $BIN/peer channel join -b $TMP/${CHANNEL_NAME}.block >& $TMP/log-joinchannel.txt
              res=$?
              set +x
              printMessage "join channel" $res
              cat $TMP/log-joinchannel.txt
              set -x
              $BIN/peer channel list
              res=$?
              set +x
              printMessage "peer channel list" $res
          envFrom:
            - configMapRef:
                name: {{ include "hlf-operator.fullname" . }}--cli
          volumeMounts:
            - mountPath: /var/hyperledger
              name: fabricfiles
            - mountPath: {{ .Values.global.workingDir }}/uploaded
              name: upload
            - mountPath: /etc/hyperledger
              name: core-yaml
            - name: setup-script
              mountPath: /script/setup.sh
              subPath: setup.sh
            - name: org0-tls-ca-cert
              mountPath: {{ .Values.global.workingDir }}/crypto-config/channel-artifacts/org0-tls-ca-cert
{{- end }}
