version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:9.6.17-alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ../deployments/dev-net/scripts/createdb.sql:/docker-entrypoint-initdb.d/1-createdb.sql
    command: postgres
    ports:
      - 5432:5432
  redis:
    container_name: redis
    image: redis:5.0.9-alpine
    volumes:
      - ../deployments/dev-net/volume/redis-data:/data
    #      - ../deployments/dev-net/volume/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
  proxy:
    build: ./proxy
    container_name: proxy
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - AUTH_HOST=http://auth:8080
      - APP_HOST=http://ui-account:3000
    ports:
      - 8080:8080
  auth:
    #    build: ./auth
    image: auth:1.0
    container_name: auth
    environment:
      - TYPEORM_HOST=postgres
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=docker
      - TYPEORM_DATABASE=auth_db
      - REDIS_HOST=redis
    depends_on:
      - redis
      - postgres
  ui-account:
    build: ./ui-account
    container_name: ui-account
    environment:
      - NODE_ENV=development
      - PORT=3000
