apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fdi.fullname" . }}-cli
  labels:
{{- include "labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fdi.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "labels.standard" . | indent 8 }}
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc-org0
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: cli
          image: "hyperledger/fabric-tools:{{ .Values.cli.image.tag }}"
          command:
            - sh
            - -c
            - "sleep 48h"
          envFrom:
            - configMapRef:
                name: {{ include "fdi.fullname" . }}--cli
          volumeMounts:
            - mountPath: /var/artifacts
              name: fabricfiles
              subPath: {{ .Values.cli.persistence.subPath }}
            - mountPath: /host/var/run/docker.sock
              name: dockersocket
