on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

name: CI

jobs:
  build:
    name: CI
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node.js for use with action
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '8.x'
          version: '8.x'
#      - name: Install dependencies
#        run: sudo apt-get install curl python make g++
      - name: yarn install
        run: yarn install --frozen-lockfile --ignore-engines
      - run: npm rebuild
      - run: yarn lint:lib
      - run: yarn lint:app
      - name: Run tsc for all packages
        run: yarn tsc:all
      - name: Run unit tests for auth-server, chaincode, fabric-cqrs, gateway-lib, model-*
        run: yarn unit-test
        env:
          CI: true
