on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

name: CI

env:
  NODE_MODULE_VERSION: 57

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node.js for use with action
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '8.x'
          version: '8.x'
      - name: yarn install
        run: yarn install --frozen-lockfile --ignore-engines
      - run: npm rebuild grpc --target=8.0.0 --target_platform=linux --target_arch=x64 --target_libc=glibc
      - run: yarn lint:lib
      - run: yarn lint:app
      - name: Run tsc for all packages
        run: yarn tsc:all
      - name: Run unit tests for auth-server, chaincode, gateway-lib, model-*
        run: yarn unit-test:no_grpc
        env:
          CI: true
# in CI environment, grpc has problem. Bypassing the unit test for fabric-cqrs, with yarn unit-test:no_grpc
#  @fabric-es/fabric-cqrs: $ node ./dist/account/enrollAdmin.js
#  @fabric-es/fabric-cqrs: /home/runner/work/fabric-es/fabric-es/node_modules/grpc/src/grpc_extension.js:55
#  @fabric-es/fabric-cqrs:     throw error;
#  @fabric-es/fabric-cqrs:     ^
#  @fabric-es/fabric-cqrs: Error: Failed to load gRPC binary module because it was not installed for the current system
#  @fabric-es/fabric-cqrs: Expected directory: node-v72-linux-x64-glibc
#  @fabric-es/fabric-cqrs: Found: [node-v57-linux-x64-glibc]
#  @fabric-es/fabric-cqrs: This problem can often be fixed by running "npm rebuild" on the current system
#  @fabric-es/fabric-cqrs: Original error: Cannot find module '/home/runner/work/fabric-es/fabric-es/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'
