name: Create Release
on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
env:
  GITHUB_SHA: ${{ github.sha }}
  AUTH_IMAGE: auth-server
  GW_1: gw-org1
  GW_2: gw-org2
  TESTER: tester

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node.js for use with action
        uses: actions/setup-node@v2
        with:
          node-version: '12.16.1'
          check-latest: true
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Run tsc for all packages
        run: yarn tsc:all
      - name: Build tester image
        run: cd /home/runner/work/fabric-es/fabric-es/deployments/dev-net && ./dn-build.tester.sh
      - name: Build org1 org2 org3 images (org1 org2 org3)
        run: cd /home/runner/work/fabric-es/fabric-es/deployments/dev-net && ./dn-build.gw.sh org1 org2 org3
      - name: Run multi-org integration test
        run: cd /home/runner/work/fabric-es/fabric-es/deployments/dev-net && ./dn-test.gw-3.sh
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CREATE_PACKAGE }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push GW-1 to GCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$GW_1
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "$default-branch" ] && VERSION=latest
          docker tag fabric-es/$GW_1 $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Push GW-2 to GCR
        run: |
          set -x
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$GW_2
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "$default-branch" ] && VERSION=latest
          docker tag fabric-es/$GW_2 $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Push Tester to GCR
        run: |
          set -x
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$TESTER
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "$default-branch" ] && VERSION=latest
          docker tag fabric-es/$TESTER $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Cleanup artifacts
        run: sudo rm -rf /home/runner/work/fabric-es/fabric-es/deployments/dev-net/artifacts
      - name: Cleanup data volume
        run: sudo rm -rf /home/runner/work/fabric-es/fabric-es/deployments/dev-net/volume
      - name: Make dev-net asset
        run: |
          set -x
          tar -czvf dev-net.tar.gz /home/runner/work/fabric-es/fabric-es/deployments/dev-net
      - name: Create Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "true"
          CHANGELOG_FILE: "none"
          ALLOW_EMPTY_CHANGELOG: "true"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            dev-net.tar.gz
      - name: Make typedoc
        run: sudo yarn typedoc && sudo touch typedocs/.nojekyll
      - name: Deploy typedoc to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.CI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: typedocs
          CLEAN: true
