name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: prepare build context - auth server
        run: cd /home/runner/work/fabric-es/fabric-es/deployments/dev-net && ./build-auth.sh
      - name: prepare build context - tester
        run: cd /home/runner/work/fabric-es/fabric-es/deployments/dev-net && ./dn-build.tester.sh
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          context: /home/runner/work/fabric-es/fabric-es/packages/auth/build
          file: /home/runner/work/fabric-es/fabric-es/packages/auth/Dockerfile
          repository: hktfp5/rl-org1
          tag_with_ref: true
