name: Node.js package
on:
  release:
    types: [released]
jobs:
  build:
    name: Publish to (public) npmjs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node.js for use with action
        uses: actions/setup-node@v2
        with:
          node-version: '12.16.1'
          registry-url: 'https://registry.npmjs.org'
          scope: '@fabric-es'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Run tsc for library packages
        run: yarn tsc:lib
      ### NOTE: fabric-cqrs depends on operator
      - name: publish - operator
        run: cd packages/operator && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish - fabric-cqrs
        run: packages/fabric-cqrs && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish - gateway-lib
        run: packages/gateway-lib && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

