name: simple
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          node-version: "8.x"
      - run: yarn install --frozen-lockfile --ignore-engines
      - run: yarn build:auth
      - run: DOCKER_BUILD=1 docker build --no-cache -f ./auth-server.dockerfile -t espresso/auth-server:1.0 .
