apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-operator.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 2375
      targetPort: 2375
      protocol: TCP
      name: docker
    - port: 7051
      targetPort: 7051
      protocol: TCP
      name: cli
  selector:
    app: {{ include "hlf-operator.name" . }}
    release: {{ .Release.Name }}
